"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Product = {
  id: number; title: string; category: string; brand: string; price: number;
  oldPrice?: number; rating: number; stock: boolean; image: string; badge?: string;
  sku: string; color: string; screen?: string; description: string;
};

const products: Product[] = [
  { id: 1, title: "Nova X12 Pro 5G Smartphone", category: "Mobile", brand: "Nova", price: 92999, oldPrice: 109999, rating: 4.9, stock: true, image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=700&q=85", badge: "-15%", sku: "IS-MOB-012", color: "blue", screen: '6.7\"', description: "Flagship 5G performance, vivid OLED display and all-day battery in a refined glass body." },
  { id: 2, title: "AeroBook 14 Performance Laptop", category: "Computers", brand: "Aero", price: 184999, oldPrice: 199999, rating: 4.8, stock: true, image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=700&q=85", badge: "HOT", sku: "IS-PC-114", color: "silver", screen: '14\"', description: "A slim performance laptop with a color-accurate display, fast SSD and quiet all-day productivity." },
  { id: 3, title: "Pulse Max Wireless Headphones", category: "Audio", brand: "Pulse", price: 18999, oldPrice: 22999, rating: 4.7, stock: true, image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=700&q=85", badge: "-18%", sku: "IS-AUD-220", color: "black", description: "Immersive over-ear audio with active noise cancellation and a 40-hour battery." },
  { id: 4, title: "Orbit S AMOLED Smart Watch", category: "Wearables", brand: "Orbit", price: 24999, rating: 4.6, stock: true, image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=85", sku: "IS-WAT-091", color: "black", screen: '1.9\"', description: "Advanced health tracking, GPS and a bright always-on AMOLED display." },
  { id: 5, title: "Vision 55\" Quantum Smart TV", category: "Television", brand: "Vision", price: 164999, oldPrice: 189999, rating: 4.8, stock: true, image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=700&q=85", badge: "-13%", sku: "IS-TV-550", color: "black", screen: '55\"', description: "Cinematic 4K quantum color, smart streaming and immersive spatial sound." },
  { id: 6, title: "GameCore Pro Wireless Controller", category: "Gaming", brand: "GameCore", price: 12999, rating: 4.7, stock: true, image: "https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=700&q=85", badge: "HOT", sku: "IS-GAM-032", color: "black", description: "Low-latency wireless control with precision triggers and ergonomic grip." },
  { id: 7, title: "FocusOne Mirrorless Camera", category: "Camera", brand: "FocusOne", price: 214999, rating: 4.9, stock: true, image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=700&q=85", sku: "IS-CAM-720", color: "black", description: "Capture remarkable detail with fast autofocus, 4K video and compact pro controls." },
  { id: 8, title: "Sonic Mini Bluetooth Speaker", category: "Audio", brand: "Sonic", price: 8999, oldPrice: 10999, rating: 4.5, stock: false, image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=700&q=85", badge: "-18%", sku: "IS-AUD-044", color: "green", description: "Room-filling portable sound in a water-resistant design made for everyday adventures." },
  { id: 9, title: "AirLink Wi-Fi 6 Smart Router", category: "Networking", brand: "AirLink", price: 15999, rating: 4.4, stock: true, image: "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?auto=format&fit=crop&w=700&q=85", sku: "IS-NET-610", color: "white", description: "Fast whole-home Wi-Fi 6 coverage with simple app controls and guest access." },
  { id: 10, title: "HomeBot Smart Vacuum", category: "Home Appliances", brand: "HomeBot", price: 74999, oldPrice: 84999, rating: 4.6, stock: true, image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=700&q=85", badge: "-12%", sku: "IS-HOM-410", color: "white", description: "Intelligent mapping, strong suction and scheduled cleaning from your phone." },
];

const blogPosts = [
  ["Future-ready tech", "How AI devices are changing the way we live", "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=900&q=80"],
  ["Mobile", "A practical guide to choosing your next smartphone", "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80"],
  ["Workspace", "Build a faster and calmer home office setup", "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80"],
  ["Gaming", "What really matters in a modern gaming setup", "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80"],
  ["Audio", "Find the right headphones for work and travel", "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80"],
  ["Smart Home", "Simple upgrades that make a home feel smarter", "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=900&q=80"],
] as const;

const money = (n: number) => `PKR ${n.toLocaleString("en-PK")}`;

export default function Storefront({ initialPath }: { initialPath: string }) {
  const [path, setPath] = useState(initialPath || "/");
  const [cart, setCart] = useState<Record<number, number>>({});
  const [wishlist, setWishlist] = useState<number[]>([]);
  const [compare, setCompare] = useState<number[]>([]);
  const [query, setQuery] = useState("");
  const [toast, setToast] = useState("");
  const [quick, setQuick] = useState<Product | null>(null);
  const [mobile, setMobile] = useState(false);

  useEffect(() => {
    try {
      setCart(JSON.parse(localStorage.getItem("is-cart") || "{}"));
      setWishlist(JSON.parse(localStorage.getItem("is-wishlist") || "[]"));
      setCompare(JSON.parse(localStorage.getItem("is-compare") || "[]"));
    } catch {}
  }, []);
  useEffect(() => { localStorage.setItem("is-cart", JSON.stringify(cart)); }, [cart]);
  useEffect(() => { localStorage.setItem("is-wishlist", JSON.stringify(wishlist)); }, [wishlist]);
  useEffect(() => { localStorage.setItem("is-compare", JSON.stringify(compare)); }, [compare]);
  useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(""), 2600); return () => clearTimeout(t); }, [toast]);

  const go = (to: string) => { history.pushState({}, "", to); setPath(to); setMobile(false); scrollTo({ top: 0, behavior: "smooth" }); };
  useEffect(() => { const fn = () => setPath(location.pathname + location.search); addEventListener("popstate", fn); return () => removeEventListener("popstate", fn); }, []);
  const addCart = (id: number, qty = 1) => { setCart(c => ({ ...c, [id]: (c[id] || 0) + qty })); setToast("Added to cart"); };
  const toggle = (kind: "wishlist" | "compare", id: number) => {
    const setter = kind === "wishlist" ? setWishlist : setCompare;
    setter((items: number[]) => items.includes(id) ? items.filter(x => x !== id) : [...items, id]);
    setToast(kind === "wishlist" ? "Wishlist updated" : "Comparison updated");
  };
  const cartCount = Object.values(cart).reduce((a, b) => a + b, 0);
  const suggestions = query.length > 1 ? products.filter(p => `${p.title} ${p.category} ${p.brand} ${p.sku} ${p.description}`.toLowerCase().includes(query.toLowerCase())).slice(0, 5) : [];

  return <div className="site-shell">
    <Header {...{ query, setQuery, suggestions, cartCount, wishlist, compare, go, mobile, setMobile }} />
    <main>
      {path === "/" && <Home {...{ go, addCart, toggle, setQuick, wishlist, compare }} />}
      {path.startsWith("/shop") && <Shop {...{ path, go, addCart, toggle, setQuick, wishlist, compare }} />}
      {path.startsWith("/product/") && <ProductPage product={products.find(p => path.includes(p.id.toString())) || products[0]} {...{ addCart, toggle, wishlist, compare }} />}
      {path === "/about" && <About go={go} />}
      {path === "/blog" && <Blog go={go} />}
      {path.startsWith("/blog/") && <BlogPost go={go} />}
      {path === "/contact" && <Contact setToast={setToast} />}
      {path === "/login" && <Auth mode="login" go={go} setToast={setToast} />}
      {path === "/signup" && <Auth mode="signup" go={go} setToast={setToast} />}
      {path === "/forgot-password" && <Auth mode="forgot" go={go} setToast={setToast} />}
      {path === "/cart" && <Cart {...{ cart, setCart, go }} />}
      {path === "/checkout" && <Checkout {...{ cart, setCart, go, setToast }} />}
      {path === "/wishlist" && <Saved title="My Wishlist" ids={wishlist} empty="Your wishlist is waiting for something special." action={id => addCart(id)} actionLabel="Move to cart" />}
      {path === "/compare" && <Compare ids={compare} addCart={addCart} />}
      {path.startsWith("/account") && <Account go={go} />}
      {path.startsWith("/admin") && <Admin setToast={setToast} />}
      {!["/", "/about", "/blog", "/contact", "/login", "/signup", "/forgot-password", "/cart", "/checkout", "/wishlist", "/compare"].some(x => path === x) && !path.startsWith("/shop") && !path.startsWith("/product/") && !path.startsWith("/blog/") && !path.startsWith("/account") && !path.startsWith("/admin") && <NotFound go={go} />}
    </main>
    {!path.startsWith("/admin") && <Footer go={go} setToast={setToast} />}
    {quick && <QuickView product={quick} close={() => setQuick(null)} addCart={addCart} />}
    {toast && <div className="toast" role="status">✓ {toast}</div>}
  </div>;
}

function Header(props: any) {
  const { query, setQuery, suggestions, cartCount, wishlist, compare, go, mobile, setMobile } = props;
  const nav = [["Home", "/"], ["Shop", "/shop"], ["About", "/about"], ["Blog", "/blog"], ["Contact", "/contact"]];
  return <header>
    <div className="topbar"><div className="wrap header-main">
      <button className="menu-btn" onClick={() => setMobile(!mobile)} aria-label="Open menu">☰</button>
      <button className="logo-btn" onClick={() => go("/")}><img src="/insight-store-logo.png" alt="Insight Store" /></button>
      <div className="search-wrap">
        <select aria-label="Search category"><option>All Categories</option><option>Mobile</option><option>Computers</option><option>Audio</option></select>
        <input value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === "Enter" && go(`/shop?q=${encodeURIComponent(query)}`)} placeholder="Search products, brands and categories" aria-label="Search products" />
        <button onClick={() => go(`/shop?q=${encodeURIComponent(query)}`)} aria-label="Submit search">⌕</button>
        {suggestions.length > 0 && <div className="suggestions">{suggestions.map((p: Product) => <button key={p.id} onClick={() => { go(`/product/${p.id}`); setQuery(""); }}><img src={p.image} alt="" /><span>{p.title}<small>{money(p.price)}</small></span></button>)}</div>}
      </div>
      <div className="hotline"><span>◉</span><b>+92 300 1234567<small>Expert help, 24/7</small></b></div>
    </div></div>
    <div className="navrow"><div className="wrap nav-inner">
      <details className="all-cats"><summary>☷ &nbsp; All Categories</summary><div>{["Mobile", "Computers", "Gaming", "Television", "Audio"].map(c => <button key={c} onClick={() => go(`/shop?category=${c}`)}>{c}<span>›</span></button>)}</div></details>
      <nav className={mobile ? "open" : ""}>{nav.map(([n, p]) => <button key={p} onClick={() => go(p)}>{n}</button>)}</nav>
      <div className="nav-actions"><button onClick={() => go("/compare")} aria-label="Compare">⇄<i>{compare.length}</i></button><button onClick={() => go("/wishlist")} aria-label="Wishlist">♡<i>{wishlist.length}</i></button><button onClick={() => go("/cart")} aria-label="Cart">🛒<i>{cartCount}</i></button><button className="account-link" onClick={() => go("/login")}>Account</button></div>
    </div></div>
  </header>;
}

function Home({ go, addCart, toggle, setQuick, wishlist, compare }: any) {
  const [slide, setSlide] = useState(0);
  useEffect(() => { const t = setInterval(() => setSlide(s => (s + 1) % 3), 5500); return () => clearInterval(t); }, []);
  const slides = [
    ["NEXT LEVEL TECH", "Smarter living starts here", "Discover powerful devices curated for work, play and everything between.", "https://images.unsplash.com/photo-1605236453806-6ff36851218e?auto=format&fit=crop&w=1600&q=85"],
    ["CREATOR EDIT", "Ideas deserve better tools", "Premium laptops and audio gear for your most ambitious projects.", "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1600&q=85"],
    ["SMART HOME", "Comfort, beautifully connected", "Effortless essentials that bring intelligence to every room.", "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1600&q=85"],
  ];
  return <>
    <div className="category-strip wrap">{["▣ Computers", "▤ Television", "♫ Audio", "▥ Mobiles", "◉ Watches", "◫ Cameras", "♬ Headphones", "◇ Gaming"].map(x => <button key={x} onClick={() => go(`/shop?category=${x.split(" ")[1]}`)}>{x}</button>)}</div>
    <section className="hero"><div className="hero-bg" style={{ backgroundImage: `linear-gradient(90deg,rgba(0,19,58,.93),rgba(0,31,86,.55),rgba(0,0,0,.08)),url('${slides[slide][3]}')` }} /><div className="wrap hero-copy"><span>{slides[slide][0]}</span><h1>{slides[slide][1]}</h1><p>{slides[slide][2]}</p><div><button className="primary" onClick={() => go("/shop")}>Shop now →</button><button className="ghost" onClick={() => go("/about")}>Explore our story</button></div></div><div className="hero-dots">{slides.map((_, i) => <button key={i} className={i === slide ? "active" : ""} onClick={() => setSlide(i)} aria-label={`Slide ${i + 1}`} />)}</div></section>
    <section className="wrap section"><SectionHead title="Popular Categories" action="View all categories" onClick={() => go("/shop")} /><div className="category-grid">{[["Mobile", "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=400&q=80"], ["Computers", "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=400&q=80"], ["Audio", "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=400&q=80"], ["Gaming", "https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=400&q=80"], ["Camera", "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=400&q=80"], ["Smart Home", "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=400&q=80"]].map(([n, img]) => <button key={n} onClick={() => go(`/shop?category=${n}`)}><img src={img} alt="" /><b>{n}</b><small>{products.filter(p => p.category.includes(n)).length || 12} products</small></button>)}</div></section>
    <section className="wrap promo-grid"><article className="promo mint"><span>FEATURED</span><h3>Sound that moves with you</h3><p>From {money(8999)}</p><button onClick={() => go("/shop?category=Audio")}>Shop audio →</button></article><article className="promo blue"><span>HOME EDIT</span><h3>Smarter spaces, simpler days</h3><p>Save up to 20%</p><button onClick={() => go("/shop?category=Home")}>Explore home →</button></article><article className="promo peach"><span>POWER PICKS</span><h3>Gear up your game</h3><p>New arrivals weekly</p><button onClick={() => go("/shop?category=Gaming")}>Shop gaming →</button></article></section>
    <ProductSection title="Today's popular picks" list={products.slice(0, 5)} {...{ go, addCart, toggle, setQuick, wishlist, compare }} />
    <section className="experience"><div className="wrap"><span>IMMERSIVE TECH</span><h2>Step into the experience</h2><p>Virtual worlds. Real possibilities. Discover next-generation gaming and wearable tech.</p><button className="primary" onClick={() => go("/shop?category=Gaming")}>Explore collection</button></div></section>
    <ProductSection title="Trending right now" list={products.slice(5, 10)} {...{ go, addCart, toggle, setQuick, wishlist, compare }} />
    <section className="wrap section"><SectionHead title="Latest from Insight" action="Read all stories" onClick={() => go("/blog")} /><div className="blog-grid home-blog">{blogPosts.slice(0, 3).map((p, i) => <BlogCard key={i} post={p} go={go} i={i} />)}</div></section>
  </>;
}

function SectionHead({ title, action, onClick }: any) { return <div className="section-head"><h2>{title}</h2><button onClick={onClick}>{action} →</button></div>; }

function ProductSection(props: any) { return <section className="wrap section"><SectionHead title={props.title} action="View all" onClick={() => props.go("/shop")} /><div className="product-grid">{props.list.map((p: Product) => <ProductCard key={p.id} p={p} {...props} />)}</div></section>; }

function ProductCard({ p, go, addCart, toggle, setQuick, wishlist, compare }: any) {
  return <article className="product-card"><div className="product-image">{p.badge && <em className={p.badge === "HOT" ? "hot" : ""}>{p.badge}</em>}<img src={p.image} alt={p.title} /><div className="card-actions"><button onClick={() => toggle("wishlist", p.id)} aria-label="Wishlist">{wishlist.includes(p.id) ? "♥" : "♡"}</button><button onClick={() => toggle("compare", p.id)} aria-label="Compare">{compare.includes(p.id) ? "✓" : "⇄"}</button><button onClick={() => setQuick(p)} aria-label="Quick view">⌕</button></div></div><small>{p.category}</small><button className="product-title" onClick={() => go(`/product/${p.id}`)}>{p.title}</button><div className="price"><b>{money(p.price)}</b>{p.oldPrice && <del>{money(p.oldPrice)}</del>}</div><div className="rating">★★★★★ <span>({p.rating})</span></div><button className="add-btn" disabled={!p.stock} onClick={() => addCart(p.id)}>{p.stock ? "Add to cart" : "Out of stock"}</button></article>;
}

function Shop({ path, go, addCart, toggle, setQuick, wishlist, compare }: any) {
  const params = new URLSearchParams(path.split("?")[1] || "");
  const [search, setSearch] = useState(params.get("q") || "");
  const [category, setCategory] = useState(params.get("category") || "All");
  const [brand, setBrand] = useState("All");
  const [max, setMax] = useState(250000);
  const [sort, setSort] = useState("popular");
  const [filters, setFilters] = useState(false);
  const list = useMemo(() => {
    let r = products.filter(p => p.price <= max && (category === "All" || p.category.toLowerCase().includes(category.toLowerCase())) && (brand === "All" || p.brand === brand) && `${p.title} ${p.category} ${p.brand}`.toLowerCase().includes(search.toLowerCase()));
    if (sort === "low") r.sort((a,b) => a.price-b.price); if (sort === "high") r.sort((a,b) => b.price-a.price); if (sort === "rated") r.sort((a,b) => b.rating-a.rating); return r;
  }, [search, category, brand, max, sort]);
  const side = <aside className={filters ? "filters open" : "filters"}><button className="filter-close" onClick={() => setFilters(false)}>×</button><h3>Filter products</h3><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search products" /><label>Price up to <b>{money(max)}</b><input type="range" min="8000" max="250000" step="1000" value={max} onChange={e => setMax(+e.target.value)} /></label><h4>Categories</h4>{["All", ...new Set(products.map(p => p.category))].map(c => <label className="check" key={c}><input type="radio" name="cat" checked={category === c} onChange={() => setCategory(c)} /> {c}</label>)}<h4>Brands</h4><select value={brand} onChange={e => setBrand(e.target.value)}><option>All</option>{[...new Set(products.map(p => p.brand))].map(b => <option key={b}>{b}</option>)}</select><h4>Availability</h4><label className="check"><input type="checkbox" /> In stock</label><label className="check"><input type="checkbox" /> On sale</label><button className="clear" onClick={() => { setSearch(""); setCategory("All"); setBrand("All"); setMax(250000); }}>Clear filters</button></aside>;
  return <div className="wrap page"><Breadcrumb items={["Home", "Shop"]} /><div className="shop-layout">{side}<section className="shop-results"><div className="shop-toolbar"><span>Showing <b>{list.length}</b> products</span><button className="filter-open" onClick={() => setFilters(true)}>☷ Filters</button><select value={sort} onChange={e => setSort(e.target.value)}><option value="popular">Most popular</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="rated">Best rated</option></select></div>{list.length ? <div className="product-grid shop-grid">{list.map(p => <ProductCard key={p.id} p={p} {...{ go, addCart, toggle, setQuick, wishlist, compare }} />)}</div> : <Empty title="No products found" text="Try clearing a filter or searching for something broader." />}<div className="pagination"><button>‹</button><button className="active">1</button><button>2</button><button>3</button><button>›</button></div></section></div></div>;
}

function ProductPage({ product: p, addCart, toggle, wishlist, compare }: any) {
  const [qty, setQty] = useState(1); const [tab, setTab] = useState("Description");
  return <div className="wrap page"><Breadcrumb items={["Home", "Shop", p.title]} /><section className="product-detail"><div className="detail-image"><img src={p.image} alt={p.title} /><span>Hover to view details</span></div><div className="detail-copy"><small>{p.category} · {p.brand}</small><h1>{p.title}</h1><div className="rating">★★★★★ <span>{p.rating} · 128 verified reviews</span></div><div className="detail-price">{money(p.price)} {p.oldPrice && <del>{money(p.oldPrice)}</del>}</div><p>{p.description}</p><dl><div><dt>SKU</dt><dd>{p.sku}</dd></div><div><dt>Availability</dt><dd className={p.stock ? "green" : "red"}>{p.stock ? "In stock" : "Out of stock"}</dd></div><div><dt>Delivery</dt><dd>2–4 business days</dd></div></dl><label className="option">Color <select><option>{p.color}</option><option>midnight</option></select></label><div className="buy-row"><div className="qty"><button onClick={() => setQty(Math.max(1, qty - 1))}>−</button><b>{qty}</b><button onClick={() => setQty(qty + 1)}>+</button></div><button className="primary" onClick={() => addCart(p.id, qty)}>Add to cart</button></div><div className="secondary-actions"><button onClick={() => toggle("wishlist", p.id)}>{wishlist.includes(p.id) ? "♥ Saved" : "♡ Add to wishlist"}</button><button onClick={() => toggle("compare", p.id)}>{compare.includes(p.id) ? "✓ Comparing" : "⇄ Compare"}</button></div></div></section><section className="tabs"><div>{["Description", "Specifications", "Reviews"].map(t => <button className={tab === t ? "active" : ""} key={t} onClick={() => setTab(t)}>{t}</button>)}</div>{tab === "Description" && <p>{p.description} Every item from Insight Store is quality checked, carefully packed and backed by responsive local support.</p>}{tab === "Specifications" && <table><tbody><tr><th>Brand</th><td>{p.brand}</td></tr><tr><th>Category</th><td>{p.category}</td></tr><tr><th>Color</th><td>{p.color}</td></tr><tr><th>Warranty</th><td>1 year official warranty</td></tr></tbody></table>}{tab === "Reviews" && <p>Rated {p.rating}/5 by verified customers. Sign in after purchase to leave a review.</p>}</section></div>;
}

function About({ go }: any) { return <div className="page"><div className="wrap"><Breadcrumb items={["Home", "About Us"]} /><section className="about-top"><div className="about-images"><img src="https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=85" alt="Insight Store team" /><b>12<small>years of<br/>experience</small></b></div><div><span className="eyebrow">ABOUT INSIGHT STORE</span><h1>Technology that makes everyday life feel more possible.</h1><p>Insight Store is a customer-first electronics destination for carefully selected devices, honest guidance and dependable after-sales support.</p><p>From smartphones and computers to smart homes and gaming, every product is selected for performance, value and lasting usefulness.</p><div className="stats"><b>25+<small>Retail partners</small></b><b>3k+<small>Monthly deliveries</small></b><b>120+<small>Trusted brands</small></b></div></div></section></div><section className="watch-banner"><div className="wrap"><span>CURATED LUXURY</span><h2>Time, beautifully engineered.</h2><button className="primary" onClick={() => go("/shop?category=Wearables")}>Shop watches</button></div></section><section className="wrap section"><SectionHead title="Loved by customers" action="Shop with confidence" onClick={() => go("/shop")} /><div className="testimonials">{["Fast delivery and the packaging was excellent.", "The team helped me choose the right laptop without upselling.", "A genuinely smooth checkout and after-sales experience."].map((t, i) => <article key={t}><div className="rating">★★★★★</div><p>“{t}”</p><b>{["Areeba Khan", "Hamza Ali", "Sara Ahmed"][i]}</b><small>Verified customer</small></article>)}</div></section></div>; }

function Blog({ go }: any) { return <div className="wrap page"><Breadcrumb items={["Home", "Blog"]} /><h1 className="page-title">Ideas, guides & inspiration</h1><div className="blog-layout"><section className="blog-grid">{blogPosts.concat(blogPosts).map((p, i) => <BlogCard key={i} post={p} go={go} i={i} />)}</section><aside className="blog-side"><input placeholder="Search stories" /><h3>Categories</h3>{["Buying guides", "Mobile", "Smart home", "Gaming", "Audio"].map(x => <button key={x}>{x}<span>›</span></button>)}<div className="side-ad"><span>EDITOR'S PICK</span><h3>Make your setup work smarter.</h3><button onClick={() => go("/shop")}>Shop now</button></div><h3>Popular tags</h3><div className="tags">{["Innovation", "Reviews", "Guides", "Workspace", "Mobile"].map(x => <button key={x}>{x}</button>)}</div></aside></div></div>; }
function BlogCard({ post, go, i }: any) { return <article className="blog-card"><button onClick={() => go(`/blog/${i + 1}`)}><img src={post[2]} alt="" /></button><small>{post[0]} · Insight Editorial</small><h3><button onClick={() => go(`/blog/${i + 1}`)}>{post[1]}</button></h3><p>Clear advice and useful ideas to help you get more from the technology around you.</p></article>; }
function BlogPost({ go }: any) { return <article className="wrap article page"><Breadcrumb items={["Home", "Blog", "How AI devices are changing the way we live"]} /><span className="eyebrow">FUTURE-READY TECH</span><h1>How AI devices are changing the way we live</h1><p className="lead">Smarter products are moving from novelty to genuinely useful companions. Here is what to look for—and what to ignore.</p><img className="article-hero" src={blogPosts[0][2]} alt="AI-powered home technology" /><p>Useful technology earns its place quietly. The best new devices reduce friction, learn sensible preferences and keep people in control. That matters more than a long list of impressive-sounding features.</p><h2>Start with the problem, not the specification</h2><p>Choose products around a real routine: a laptop that stays responsive through a workday, headphones that make calls clearer, or a smart-home system that simplifies repetitive tasks. A focused product usually outperforms a complicated one.</p><blockquote>Good technology should create time and confidence—not another thing to manage.</blockquote><p>At Insight Store, our buying guides combine hands-on evaluation with practical ownership advice so you can compare the details that actually change the experience.</p><button className="primary" onClick={() => go("/blog")}>← Back to all stories</button></article>; }

function Contact({ setToast }: any) { const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); try { await fetch("/api/messages", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data) }); } catch {} e.currentTarget.reset(); setToast("Message sent — we'll be in touch shortly"); }; return <div className="wrap page"><Breadcrumb items={["Home", "Contact"]} /><h1 className="page-title">Contact Information</h1><div className="contact-cards">{[["⌖", "Corporate Office", "Gulberg III, Lahore, Pakistan"], ["▣", "Main Warehouse", "Sundar Industrial Estate, Lahore"], ["✉", "Email Address", "hello@insightstore.pk"], ["☎", "Phone Number", "+92 300 1234567"]].map(x => <article key={x[1]}><i>{x[0]}</i><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div><div className="contact-main"><form onSubmit={submit}><div><label>Name<input required name="name" /></label><label>Email<input required type="email" name="email" /></label></div><div><label>Phone<input name="phone" /></label><label>Subject<input required name="subject" /></label></div><label>Write message<textarea required name="message" rows={6} /></label><button className="primary">Send message</button></form><div className="map"><span>Insight Store Lahore</span><strong>31.5204° N<br/>74.3587° E</strong><a href="https://www.openstreetmap.org/?mlat=31.5204&mlon=74.3587#map=13/31.5204/74.3587" target="_blank" rel="noreferrer">Open interactive map →</a></div></div></div>; }

function Auth({ mode, go, setToast }: any) { const signup = mode === "signup", forgot = mode === "forgot"; const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setToast(forgot ? "Reset link sent" : signup ? "Account created — check your email" : "Welcome back"); go(forgot || signup ? "/login" : "/account"); }; return <div className="wrap page auth-page"><Breadcrumb items={["Home", forgot ? "Forgot Password" : signup ? "Signup" : "Login"]} /><h1>{forgot ? "Reset your password" : signup ? "Create your account" : "Login to your account"}</h1><form onSubmit={submit} className="auth-card">{signup && <><label>Full name<input required name="name" /></label><label>Phone<input required name="phone" /></label></>}<label>Email<input required type="email" name="email" /></label>{!forgot && <label>Password<input required minLength={8} type="password" name="password" /></label>}<button className="primary">{forgot ? "Send reset link" : signup ? "Sign up" : "Log in"}</button>{!forgot && <><div className="or">or continue with</div><button type="button" className="social" onClick={() => setToast("Google sign-in requires provider credentials")}>G &nbsp; Google</button><button type="button" className="social" onClick={() => setToast("Facebook sign-in requires provider credentials")}>f &nbsp; Facebook</button><label className="remember"><input type="checkbox" /> Remember me</label></>}<p>{forgot ? <button type="button" onClick={() => go("/login")}>Back to login</button> : signup ? <>Already have an account? <button type="button" onClick={() => go("/login")}>Login here</button></> : <>New here? <button type="button" onClick={() => go("/signup")}>Create an account</button> · <button type="button" onClick={() => go("/forgot-password")}>Forgot password?</button></>}</p></form></div>; }

function Cart({ cart, setCart, go }: any) { const items = products.filter(p => cart[p.id]); const subtotal = items.reduce((s, p) => s + p.price * cart[p.id], 0); return <div className="wrap page"><Breadcrumb items={["Home", "Cart"]} /><h1 className="page-title">Your cart</h1>{items.length ? <div className="cart-layout"><div>{items.map(p => <article className="cart-item" key={p.id}><img src={p.image} alt="" /><div><h3>{p.title}</h3><small>{p.sku}</small><b>{money(p.price)}</b></div><div className="qty"><button onClick={() => setCart((c: any) => ({ ...c, [p.id]: Math.max(1, c[p.id]-1) }))}>−</button><b>{cart[p.id]}</b><button onClick={() => setCart((c: any) => ({ ...c, [p.id]: c[p.id]+1 }))}>+</button></div><button className="remove" onClick={() => setCart((c: any) => { const n={...c}; delete n[p.id]; return n; })}>Remove</button></article>)}</div><OrderBox subtotal={subtotal} checkout={() => go("/checkout")} /></div> : <Empty title="Your cart is empty" text="Great products are only a click away." action={() => go("/shop")} />}</div>; }
function OrderBox({ subtotal, checkout }: any) { const shipping = subtotal >= 100000 ? 0 : 500; const tax = Math.round(subtotal * .02); return <aside className="order-box"><h3>Order summary</h3><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Shipping</span><b>{shipping ? money(shipping) : "Free"}</b></div><div><span>Tax estimate</span><b>{money(tax)}</b></div><div className="total"><span>Total</span><b>{money(subtotal+shipping+tax)}</b></div><input placeholder="Coupon code" /><button className="primary" onClick={checkout}>Proceed to checkout</button></aside>; }
function Checkout({ cart, setCart, go, setToast }: any) { const items=products.filter(p => cart[p.id]); const subtotal=items.reduce((s,p)=>s+p.price*cart[p.id],0); const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); setCart({}); setToast("Order placed successfully"); go("/account/orders");}; return <div className="wrap page"><Breadcrumb items={["Home", "Cart", "Checkout"]} /><h1 className="page-title">Secure checkout</h1>{!items.length ? <Empty title="Nothing to check out" text="Add a product to your cart first." action={() => go("/shop")} /> : <form className="checkout" onSubmit={submit}><section><h2>Billing & delivery</h2><div className="form-grid">{["First name","Last name","Email","Phone","City","Postal code"].map(x=><label key={x}>{x}<input required type={x==="Email"?"email":"text"}/></label>)}</div><label>Delivery address<textarea required rows={3}/></label><h2>Payment</h2>{["Cash on delivery","Bank transfer","Card payment (configuration ready)"].map((x,i)=><label className="pay" key={x}><input type="radio" name="payment" defaultChecked={!i}/><span><b>{x}</b><small>{i===0?"Pay when your order arrives":"Secure instructions appear after order confirmation"}</small></span></label>)}</section><OrderBox subtotal={subtotal} checkout={()=>{}}/><button className="primary place-order">Place order</button></form>}</div>; }

function Saved({ title, ids, empty, action, actionLabel }: any) { const list=products.filter(p=>ids.includes(p.id)); return <div className="wrap page"><Breadcrumb items={["Home", title]} /><h1 className="page-title">{title}</h1>{list.length?<div className="saved-grid">{list.map(p=><article key={p.id}><img src={p.image} alt=""/><div><small>{p.category}</small><h3>{p.title}</h3><b>{money(p.price)}</b></div><button className="primary" onClick={()=>action(p.id)}>{actionLabel}</button></article>)}</div>:<Empty title={`No items in ${title.toLowerCase()}`} text={empty}/>}</div>; }
function Compare({ ids, addCart }: any) { const list=products.filter(p=>ids.includes(p.id)); return <div className="wrap page"><Breadcrumb items={["Home","Compare"]}/><h1 className="page-title">Compare products</h1>{list.length?<div className="compare-table"><table><thead><tr><th>Feature</th>{list.map(p=><th key={p.id}><img src={p.image} alt=""/><b>{p.title}</b></th>)}</tr></thead><tbody>{[["Price",(p:Product)=>money(p.price)],["Brand",(p:Product)=>p.brand],["Rating",(p:Product)=>`${p.rating}/5`],["Stock",(p:Product)=>p.stock?"In stock":"Out of stock"]].map(([n,fn]:any)=><tr key={n}><th>{n}</th>{list.map(p=><td key={p.id}>{fn(p)}</td>)}</tr>)}<tr><th>Action</th>{list.map(p=><td key={p.id}><button className="primary" onClick={()=>addCart(p.id)}>Add to cart</button></td>)}</tr></tbody></table></div>:<Empty title="Nothing to compare yet" text="Add products from the shop to see them side by side."/>}</div>; }

function Account({ go }: any) { return <div className="wrap page account"><aside><h3>My account</h3>{[["Overview","/account"],["Orders","/account/orders"],["Profile","/account/profile"],["Addresses","/account/addresses"],["Wishlist","/wishlist"]].map(x=><button key={x[0]} onClick={()=>go(x[1])}>{x[0]}<span>›</span></button>)}<button onClick={()=>go("/")}>Log out</button></aside><section><span className="eyebrow">WELCOME BACK</span><h1>Account overview</h1><div className="account-stats"><article><b>3</b><span>Total orders</span></article><article><b>1</b><span>In progress</span></article><article><b>{money(252997)}</b><span>Total spent</span></article></div><h2>Recent orders</h2><div className="order-row"><b>#IS-10428</b><span>12 Aug 2026</span><span className="pill">Processing</span><b>{money(92999)}</b></div><div className="order-row"><b>#IS-10387</b><span>29 Jul 2026</span><span className="pill delivered">Delivered</span><b>{money(24999)}</b></div></section></div>; }

function Admin({ setToast }: any) { const [view,setView]=useState("Dashboard"); const [rows,setRows]=useState(products); return <div className="admin"><aside><img src="/insight-store-logo.png" alt="Insight Store"/><small>STORE ADMIN</small>{["Dashboard","Products","Orders","Customers","Categories","Brands","Coupons","Blog","Messages","Newsletter","Settings"].map(x=><button className={view===x?"active":""} key={x} onClick={()=>setView(x)}>{x}<span>›</span></button>)}<a href="/">View storefront ↗</a></aside><main><header><div><small>INSIGHT STORE</small><h1>{view}</h1></div><button onClick={()=>setToast("Notifications are up to date")}>🔔</button><b>Admin User</b></header>{view==="Dashboard"?<><div className="admin-stats">{[["Total revenue",money(2845000),"+12.8%"],["Orders","1,284","+8.2%"],["Customers","3,902","+18.4%"],["Low stock","6","Review"]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></article>)}</div><div className="chart-card"><h2>Revenue overview</h2><div className="bars">{[42,58,48,76,63,82,71,93,86,98,88,100].map((h,i)=><i key={i} style={{height:`${h}%`}}><span>{["Sep","Oct","Nov","Dec","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug"][i]}</span></i>)}</div></div><AdminOrders/></>:view==="Products"?<section className="admin-table"><div><h2>Product catalogue</h2><button className="primary" onClick={()=>setToast("New product editor opened")}>+ Add product</button></div><table><thead><tr><th>Product</th><th>SKU</th><th>Price</th><th>Stock</th><th></th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><img src={p.image} alt=""/><b>{p.title}</b></td><td>{p.sku}</td><td>{money(p.price)}</td><td><span className={p.stock?"green":"red"}>{p.stock?"In stock":"Out"}</span></td><td><button onClick={()=>setToast(`Editing ${p.title}`)}>Edit</button><button onClick={()=>setRows(r=>r.filter(x=>x.id!==p.id))}>Delete</button></td></tr>)}</tbody></table></section>:<section className="admin-placeholder"><h2>{view} management</h2><p>Search, create, update and organize {view.toLowerCase()} from this workspace.</p><button className="primary" onClick={()=>setToast(`${view} record created`)}>Create new</button><AdminOrders/></section>}</main></div>; }
function AdminOrders(){return <section className="admin-table"><div><h2>Recent orders</h2><button>View all</button></div><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody>{[["#IS-10428","Areeba Khan",92999,"Processing"],["#IS-10427","Hamza Ali",184999,"Confirmed"],["#IS-10426","Sara Ahmed",24999,"Delivered"]].map(x=><tr key={x[0] as string}><td><b>{x[0]}</b></td><td>{x[1]}</td><td>{money(x[2] as number)}</td><td><span className="pill">{x[3]}</span></td></tr>)}</tbody></table></section>}

function QuickView({ product:p, close, addCart }: any) { const [qty,setQty]=useState(1); return <div className="modal-backdrop" onMouseDown={close}><div className="quick-modal" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true"><button className="modal-close" onClick={close}>×</button><img src={p.image} alt={p.title}/><div><small>{p.category}</small><h2>{p.title}</h2><div className="rating">★★★★★ <span>{p.rating}</span></div><div className="detail-price">{money(p.price)}</div><p>{p.description}</p><div className="buy-row"><div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))}>−</button><b>{qty}</b><button onClick={()=>setQty(qty+1)}>+</button></div><button className="primary" onClick={()=>{addCart(p.id,qty);close();}}>Add to cart</button></div></div></div></div>; }
function Breadcrumb({items}:any){return <div className="breadcrumb">{items.map((x:string,i:number)=><span key={x}>{i>0&&" / "}{x}</span>)}</div>}
function Empty({title,text,action}:any){return <div className="empty"><div>◇</div><h2>{title}</h2><p>{text}</p>{action&&<button className="primary" onClick={action}>Browse products</button>}</div>}
function NotFound({go}:any){return <div className="not-found"><div className="lost-mark">4<span>◇</span>4</div><h1>Oops! That page can not be found.</h1><p>The page may have moved, but the best of Insight Store is still right here.</p><button onClick={()=>history.back()}>← Go back</button><button className="primary" onClick={()=>go("/")}>Go to homepage</button></div>}

function Footer({go,setToast}:any){const subscribe=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const email=new FormData(e.currentTarget).get("email");try{await fetch("/api/newsletter",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});}catch{}e.currentTarget.reset();setToast("You're on the Insight list");};return <footer><div className="benefits"><div className="wrap">{[["▧","Same-day delivery"],["◎","Secure payments"],["〽","Expert guidance"],["▣","Official warranty"],["☎","24/7 support"]].map(x=><div key={x[1]}><i>{x[0]}</i><b>{x[1]}</b></div>)}</div></div><div className="footer-main"><div className="wrap footer-grid"><div className="footer-brand"><img src="/insight-store-logo.png" alt="Insight Store"/><b>+92 300 1234567</b><p>Gulberg III, Lahore, Pakistan<br/>hello@insightstore.pk</p><div>● &nbsp; ● &nbsp; ● &nbsp; ●</div></div>{[["Resources",[["About Us","/about"],["Shop","/shop"],["Cart","/cart"],["Brands","/shop"]]],["Support",[["Contact","/contact"],["Returns","/about"],["My account","/account"],["Wishlist","/wishlist"]]],["Store info",[["Best sellers","/shop"],["New arrivals","/shop"],["Compare","/compare"],["Admin","/admin"]]]].map(([h,links]:any)=><div className="footer-links" key={h}><h3>{h}</h3>{links.map((x:any)=><button key={x[0]} onClick={()=>go(x[1])}>{x[0]}</button>)}</div>)}<div className="newsletter"><h3>Stay in the know</h3><p>New tech, useful guides and members-only offers.</p><form onSubmit={subscribe}><input required type="email" name="email" placeholder="Email address"/><button>→</button></form></div></div><div className="wrap footer-bottom"><span>© 2026 Insight Store. All rights reserved.</span><b>VISA &nbsp; Mastercard &nbsp; COD &nbsp; Bank Transfer</b></div></div></footer>}
