"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import AdminPanel from "./admin-panel";
import {
  ArrowLeft, ArrowLeftRight, ArrowRight, BadgeCheck, Bell, Box, Camera,
  Check, ChevronLeft, ChevronRight, CircleUserRound, CreditCard, Eye,
  Gamepad2, Globe2, Grid3X3, Headphones, Headset, Heart,
  HousePlug, Laptop, Mail, MapPin, Menu, Monitor, CloudDownload,
  Music2, PackageCheck, PackageOpen, Phone, Search, ShieldCheck,
  ShoppingCart, SlidersHorizontal, Smartphone, Sparkles, Truck, Tv,
  UploadCloud, Copy, CheckCircle2, Watch, Warehouse, X,
} from "lucide-react";

const Facebook = Globe2;
const Instagram = Mail;
const Linkedin = Phone;
const Youtube = Headphones;

type Product = {
  id: number; title: string; category: string; brand: string; price: number;
  oldPrice?: number; rating: number; stock: boolean; image: string; badge?: string;
  sku: string; color: string; screen?: string; description: string; images?: string[]; videoUrl?: string; stockQuantity?: number; isDigital?: boolean;
};

const forceWebp = (src: string) => {
  const localWebp = src.replace(/\.png(?=($|\?))/i, ".webp");
  return localWebp.includes("images.unsplash.com") && !localWebp.includes("fm=webp")
    ? `${localWebp}${localWebp.includes("?") ? "&" : "?"}fm=webp`
    : localWebp;
};

const products: Product[] = [
  { id: 1, title: "Nova X12 Pro 5G Smartphone", category: "Mobile", brand: "Nova", price: 92999, oldPrice: 109999, rating: 4.9, stock: true, image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=700&q=85", badge: "-15%", sku: "IS-MOB-012", color: "blue", screen: '6.7\"', description: "Flagship 5G performance, vivid OLED display and all-day battery in a refined glass body." },
  { id: 2, title: "AeroBook 14 Performance Laptop", category: "Computers", brand: "Aero", price: 184999, oldPrice: 199999, rating: 4.8, stock: true, image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=700&q=85", badge: "HOT", sku: "IS-PC-114", color: "silver", screen: '14\"', description: "A slim performance laptop with a color-accurate display, fast SSD and quiet all-day productivity." },
  { id: 3, title: "Pulse Max Wireless Headphones", category: "Audio", brand: "Pulse", price: 18999, oldPrice: 22999, rating: 4.7, stock: true, image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=700&q=85", badge: "-18%", sku: "IS-AUD-220", color: "black", description: "Immersive over-ear audio with active noise cancellation and a 40-hour battery." },
  { id: 4, title: "Orbit S AMOLED Smart Watch", category: "Wearables", brand: "Orbit", price: 24999, rating: 4.6, stock: true, image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=85", sku: "IS-WAT-091", color: "black", screen: '1.9\"', description: "Advanced health tracking, GPS and a bright always-on AMOLED display." },
  { id: 5, title: "Vision 55\" Quantum Smart TV", category: "Television", brand: "Vision", price: 164999, oldPrice: 189999, rating: 4.8, stock: true, image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=700&q=85", badge: "-13%", sku: "IS-TV-550", color: "black", screen: '55\"', description: "Cinematic 4K quantum color, smart streaming and immersive spatial sound." },
  { id: 6, title: "GameCore Pro Wireless Controller", category: "Gaming", brand: "GameCore", price: 12999, rating: 4.7, stock: true, image: "https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=700&q=85", badge: "HOT", sku: "IS-GAM-032", color: "black", description: "Low-latency wireless control with precision triggers and ergonomic grip." },
  { id: 7, title: "FocusOne Mirrorless Camera", category: "Camera", brand: "FocusOne", price: 214999, rating: 4.9, stock: true, image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=700&q=85", sku: "IS-CAM-720", color: "black", description: "Capture remarkable detail with fast autofocus, 4K video and compact pro controls." },
  { id: 8, title: "Sonic Mini Bluetooth Speaker", category: "Audio", brand: "Sonic", price: 8999, oldPrice: 10999, rating: 4.5, stock: false, image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=700&q=85", badge: "-18%", sku: "IS-AUD-044", color: "green", description: "Room-filling portable sound in a water-resistant design made for everyday adventures." },
  { id: 9, title: "AirLink Wi-Fi 6 Smart Router", category: "Networking", brand: "AirLink", price: 15999, rating: 4.4, stock: true, image: "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?auto=format&fit=crop&w=700&q=85", sku: "IS-NET-610", color: "white", description: "Fast whole-home Wi-Fi 6 coverage with simple app controls and guest access." },
  { id: 10, title: "HomeBot Smart Vacuum", category: "Home Appliances", brand: "HomeBot", price: 74999, oldPrice: 84999, rating: 4.6, stock: true, image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=700&q=85", badge: "-12%", sku: "IS-HOM-410", color: "white", description: "Intelligent mapping, strong suction and scheduled cleaning from your phone." },
  { id: 11, title: "Premium Non-Stick Cookware Set", category: "Kitchen Accessories", brand: "ChefCraft", price: 18999, oldPrice: 22999, rating: 4.8, stock: true, image: "/images/category-kitchen.webp", badge: "-17%", sku: "IS-KIT-101", color: "black", description: "A versatile non-stick cookware set with even heat distribution and comfortable stay-cool handles." },
  { id: 12, title: "Acacia Wood Kitchen Utensil Set", category: "Kitchen Accessories", brand: "HomeChef", price: 5499, rating: 4.6, stock: true, image: "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=700&q=85", sku: "IS-KIT-102", color: "brown", description: "Durable natural wood utensils for stirring, serving and everyday cooking without scratching cookware." },
  { id: 13, title: "Stainless Steel Cooking Pot 5L", category: "Kitchen Accessories", brand: "SteelPro", price: 8999, rating: 4.7, stock: true, image: "/images/category-kitchen.webp", sku: "IS-KIT-103", color: "silver", description: "Heavy-duty stainless steel pot with tempered glass lid, ideal for family meals and batch cooking." },
  { id: 14, title: "Embroidered Women's Lawn Suit", category: "Ladies & Gents Clothes", brand: "Aangan", price: 6999, oldPrice: 7999, rating: 4.8, stock: true, image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=700&q=85", badge: "NEW", sku: "IS-FAS-201", color: "teal", description: "A graceful three-piece embroidered lawn suit with breathable fabric and refined seasonal detailing." },
  { id: 15, title: "Men's Premium Cotton Kurta", category: "Ladies & Gents Clothes", brand: "Riwaaj", price: 4499, rating: 4.7, stock: true, image: "https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=700&q=85", sku: "IS-FAS-202", color: "navy", description: "A tailored cotton kurta with clean finishing, a comfortable cut and timeless everyday style." },
  { id: 16, title: "Classic Everyday Co-Ord Set", category: "Ladies & Gents Clothes", brand: "Form", price: 5999, rating: 4.5, stock: true, image: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=700&q=85", sku: "IS-FAS-203", color: "beige", description: "A polished and versatile matching set designed for effortless comfort from day to evening." },
  { id: 17, title: "Soft Plush Teddy Bear 60cm", category: "Toys", brand: "CuddleCo", price: 3999, rating: 4.9, stock: true, image: "https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=700&q=85", badge: "BESTSELLER", sku: "IS-TOY-301", color: "brown", description: "A wonderfully soft, child-safe teddy bear made for comforting hugs, playtime and gifting." },
  { id: 18, title: "Colorful Wooden Stacking Rings", category: "Toys", brand: "BrightSteps", price: 2499, rating: 4.7, stock: true, image: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=700&q=85", sku: "IS-TOY-302", color: "multicolor", description: "An engaging early-learning toy that builds coordination, color recognition and problem-solving skills." },
  { id: 19, title: "Remote Control Sports Car", category: "Toys", brand: "TurboKids", price: 7499, oldPrice: 8999, rating: 4.6, stock: true, image: "https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=700&q=85", badge: "-17%", sku: "IS-TOY-303", color: "red", description: "A fast rechargeable remote-control car with responsive steering and durable impact-resistant body." },
  { id: 20, title: "43-inch 4K Frameless Smart TV", category: "Electronics", brand: "Vision", price: 104999, oldPrice: 119999, rating: 4.8, stock: true, image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=700&q=85", badge: "-13%", sku: "IS-ELC-401", color: "black", screen: "43-inch", description: "A crisp 4K smart television with a frameless display, popular streaming apps and cinematic sound." },
  { id: 21, title: "Digital Air Fryer 6L", category: "Electronics", brand: "CookSmart", price: 29999, rating: 4.7, stock: true, image: "/images/category-appliances.webp", sku: "IS-ELC-402", color: "black", description: "Prepare crisp family meals with less oil using eight presets and precise digital temperature control." },
  { id: 22, title: "Compact Solo Microwave Oven", category: "Electronics", brand: "HeatWave", price: 31999, rating: 4.6, stock: true, image: "https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=700&q=85", sku: "IS-ELC-403", color: "black", description: "A reliable compact microwave with quick-start controls, multiple power levels and easy-clean interior." },
  { id: 23, title: "Active Noise Cancelling Headphones", category: "Gadgets", brand: "Pulse", price: 21999, oldPrice: 25999, rating: 4.8, stock: true, image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=700&q=85", badge: "-15%", sku: "IS-GAD-501", color: "black", description: "Premium wireless headphones with immersive audio, clear calls and all-day listening comfort." },
  { id: 24, title: "FitPro Health Smartwatch", category: "Gadgets", brand: "FitPro", price: 15999, rating: 4.7, stock: true, image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=85", sku: "IS-GAD-502", color: "black", description: "Track heart rate, sleep and daily activity on a bright display with multi-day battery life." },
  { id: 25, title: "Pocket Wireless Earbuds Pro", category: "Gadgets", brand: "AirBeat", price: 9999, rating: 4.6, stock: true, image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=700&q=85", sku: "IS-GAD-503", color: "white", description: "Compact true-wireless earbuds with touch controls, clear voice calls and pocket-ready charging case." },
  { id: 26, title: "Nordic Ceramic Vase Set", category: "Home Decor", brand: "Nest", price: 6499, rating: 4.8, stock: true, image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=700&q=85", sku: "IS-DEC-601", color: "cream", description: "A sculptural ceramic vase duo that brings soft texture and a refined modern accent to any room." },
  { id: 27, title: "Modern Bedside Table Lamp", category: "Home Decor", brand: "Luma", price: 7999, rating: 4.7, stock: true, image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=85", sku: "IS-DEC-602", color: "white", description: "Warm ambient light in a clean contemporary silhouette, perfect for bedrooms and reading corners." },
  { id: 28, title: "Artificial Olive Plant with Pot", category: "Home Decor", brand: "GreenNest", price: 4999, rating: 4.5, stock: true, image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=700&q=85", sku: "IS-DEC-603", color: "green", description: "A lifelike low-maintenance plant that adds year-round greenery to homes, offices and entryways." },
  { id: 29, title: "Royal Blue Zircon Necklace Set", category: "Jewellery", brand: "Noor", price: 12999, oldPrice: 15999, rating: 4.9, stock: true, image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=700&q=85", badge: "-19%", sku: "IS-JWL-701", color: "blue", description: "A statement necklace and earring set featuring deep blue stones in an elegant gold-tone setting." },
  { id: 30, title: "Minimal Gold-Plated Bracelet", category: "Jewellery", brand: "Aura", price: 4999, rating: 4.7, stock: true, image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=700&q=85", sku: "IS-JWL-702", color: "gold", description: "An elegant lightweight bracelet with a polished finish for effortless daily and occasion styling." },
  { id: 31, title: "Pearl Drop Earring Pair", category: "Jewellery", brand: "Pearl & Co", price: 3499, rating: 4.6, stock: true, image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=700&q=85", sku: "IS-JWL-703", color: "white", description: "Timeless pearl drop earrings with a graceful profile and secure, comfortable fastening." },
  { id: 32, title: "High-Speed Blender 1200W", category: "Home Appliances", brand: "BlendMax", price: 19999, rating: 4.7, stock: true, image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=700&q=85", sku: "IS-APP-801", color: "black", description: "A powerful multi-speed blender for smoothies, sauces and crushing ice with an easy-clean glass jug." },
  { id: 33, title: "SteamGlide Ceramic Iron", category: "Home Appliances", brand: "SteamGlide", price: 8999, rating: 4.6, stock: true, image: "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=700&q=85", sku: "IS-APP-802", color: "blue", description: "Fast heat-up, continuous steam and a smooth ceramic soleplate for effortless crease removal." },
  { id: 34, title: "QuietBreeze Pedestal Fan", category: "Home Appliances", brand: "Breeze", price: 14999, rating: 4.5, stock: true, image: "/images/category-appliances.webp", sku: "IS-APP-803", color: "white", description: "Quiet, powerful airflow with adjustable height, oscillation and three practical speed settings." },
  { id: 35, title: "Rechargeable Handheld Milk Frother", category: "Kitchen Accessories", brand: "WhiskPro", price: 1050, oldPrice: 1300, rating: 4.8, stock: true, image: "/images/products/milk-frother.webp", badge: "SALE", sku: "IS-KIT-104", color: "black", description: "A rechargeable coffee beater and milk frother with three interchangeable stainless-steel whisk attachments and convenient USB charging." },
  { id: 36, title: "Big Sitting Panda Night Lamp", category: "Home Decor", brand: "LumaPanda", price: 1650, oldPrice: 2350, rating: 4.8, stock: true, image: "/images/products/panda-night-lamp.webp", badge: "SALE", sku: "IS-DEC-604", color: "multicolor", description: "A soft-glow sitting panda night lamp that creates a warm, comforting ambience for bedrooms, nurseries and gifting." },
  { id: 37, title: "Trendy Glasses with -1.00 Lens", category: "Ladies & Gents Clothes", brand: "UrbanView", price: 999, rating: 4.6, stock: true, image: "/images/products/trendy-glasses.webp", badge: "NEW", sku: "IS-FAS-204", color: "black", description: "Statement geometric eyeglasses with clear -1.00 lenses, slim black rims and refined gold-tone bridge and temples." },
  { id: 38, title: "Trendy Ear Studs & Earrings Set", category: "Jewellery", brand: "Aura", price: 550, rating: 4.7, stock: true, image: "/images/products/earring-set.webp", badge: "NEW", sku: "IS-JWL-704", color: "gold", description: "A versatile gold-tone earring collection with classic studs, pearl and crystal pairs, hoops and modern geometric designs." },
  { id: 39, title: "Pleated Ladies Evening Clutch", category: "Ladies & Gents Clothes", brand: "Élan", price: 750, rating: 4.7, stock: true, image: "/images/products/ladies-clutch.webp", badge: "NEW", sku: "IS-FAS-205", color: "white", description: "An elegant ivory evening clutch with a structured shape, fine pleated satin texture and discreet polished clasp." },
  { id: 40, title: "Adjustable Stainless-Steel Steamer Basket", category: "Kitchen Accessories", brand: "SteamNest", price: 750, rating: 4.6, stock: true, image: "/images/products/adjustable-steamer.webp", badge: "NEW", sku: "IS-KIT-105", color: "silver", description: "A collapsible stainless-steel steamer basket with expandable perforated petals, folding feet and a convenient lifting ring." },
  { id: 41, title: "Multi-Purpose Mini Remote Control", category: "Electronics", brand: "UniControl", price: 250, rating: 4.5, stock: true, image: "/images/products/universal-remote.webp", badge: "NEW", sku: "IS-ELC-404", color: "black", description: "A compact universal remote-control key fob with tactile controls, durable black-and-silver housing and a practical key ring." },
  { id: 42, title: "Magnetic 3-in-1 USB Charging Cable", category: "Gadgets", brand: "MagLink", price: 450, rating: 4.7, stock: true, image: "/images/products/magnetic-cable.webp", badge: "NEW", sku: "IS-GAD-504", color: "red", description: "A durable braided magnetic charging cable with interchangeable USB-C, Micro-USB and Lightning tips for everyday convenience." },
  { id: 43, title: "Ladies Fashion Ring Collection", category: "Jewellery", brand: "Noor", price: 250, rating: 4.8, stock: true, image: "/images/products/ladies-rings.webp", badge: "NEW", sku: "IS-JWL-705", color: "multicolor", description: "Choose a statement ring for PKR 250 each, or collect the complete eight-ring assortment for PKR 1,750. Designs include crystal, emerald-tone, infinity and turquoise styles." },
  { id: 44, title: "Rechargeable USB Kitchen Lighter", category: "Kitchen Accessories", brand: "FlameFlex", price: 650, oldPrice: 700, rating: 4.8, stock: true, image: "/images/products/usb-kitchen-lighter.webp", badge: "NEW", sku: "IS-KIT-106", color: "black", description: "A rechargeable flameless kitchen lighter with a flexible metal neck, safety controls, LED battery indicator and convenient USB charging cable." },
  { id: 45, title: "Hot & Cold Water Bottle 500ml", category: "Kitchen Accessories", brand: "Floretta", price: 900, oldPrice: 1400, rating: 4.7, stock: true, image: "/images/products/hot-cool-bottle.webp", badge: "SALE", sku: "IS-KIT-107", color: "green", description: "A compact reusable 500ml metallic bottle with secure loop cap, ideal for keeping everyday drinks conveniently close." },
  { id: 46, title: "Designer Press-On Nail — Single Piece", category: "Jewellery", brand: "Nail Studio", price: 200, rating: 4.8, stock: true, image: "/images/products/press-on-nails.webp", badge: "NEW", sku: "IS-JWL-706", color: "pink", description: "Choose one reusable designer press-on nail for PKR 200. Available designs include French tips, pearls, rhinestones, bows and delicate floral accents." },
  { id: 47, title: "Designer Press-On Nails — Set of 10", category: "Jewellery", brand: "Nail Studio", price: 1500, rating: 4.9, stock: true, image: "/images/products/press-on-nails.webp", badge: "BEST VALUE", sku: "IS-JWL-707", color: "pink", description: "A coordinated set of 10 reusable press-on nails for PKR 1,500, featuring elegant nude-pink finishes with pearls, crystals, bows and floral detailing." },
  { id: 48, title: "N°5 Eau de Parfum 100ml", category: "Ladies & Gents Clothes", brand: "Chanel", price: 10200, oldPrice: 29200, rating: 4.8, stock: true, image: "/images/products/n5-perfume.webp", badge: "SALE", sku: "IS-FAS-206", color: "blush", description: "A classic 100ml eau de parfum presentation with an elegant floral fragrance profile, refined glass bottle and premium gift-ready box." },
  { id: 49, title: "Portable Mini Air Cooler Fan", category: "Home Appliances", brand: "CoolMist", price: 2900, oldPrice: 3700, rating: 4.6, stock: true, image: "/images/products/mini-air-cooler.webp", badge: "SALE", sku: "IS-APP-804", color: "white", description: "A compact tabletop air cooler with front fan, translucent water tank, simple controls and soft ambient light for personal cooling." },
  { id: 50, title: "Rapid-Speed USB Data Cable", category: "Gadgets", brand: "RapidLink", price: 750, rating: 4.6, stock: true, image: "/images/products/rapid-data-cable.webp", badge: "NEW", sku: "IS-GAD-505", color: "multicolor", description: "A reinforced fast-charging USB data cable designed for reliable daily charging and data transfer with durable connector protection." },
  { id: 51, title: "Large Square Soap Dispenser", category: "Home Appliances", brand: "PurePump", price: 900, oldPrice: 1150, rating: 4.7, stock: true, image: "/images/products/soap-dispenser.webp", badge: "SALE", sku: "IS-APP-805", color: "white", description: "A generous clear soap dispenser with a modern rounded-square frame, smooth pump action and visible reservoir for kitchens and bathrooms." },
  { id: 52, title: "Extendable Flexible Duster Brush", category: "Home Appliances", brand: "CleanReach", price: 800, oldPrice: 1150, rating: 4.7, stock: true, image: "/images/products/extendable-duster.webp", badge: "SALE", sku: "IS-APP-806", color: "grey", description: "A telescopic microfiber duster with a flexible bendable head for cleaning ceilings, windows, wardrobes, cabinets and difficult corners." },
  { id: 53, title: "Silicone Sink Splash Guard 15-inch", category: "Kitchen Accessories", brand: "SinkShield", price: 500, oldPrice: 650, rating: 4.6, stock: true, image: "/images/products/sink-splash-guard.webp", badge: "SALE", sku: "IS-KIT-108", color: "green", description: "A flexible 15-inch silicone faucet mat that catches splashes, promotes drainage and helps keep the sink area dry and tidy." },
  { id: 54, title: "3-in-1 Universal Charging Cable", category: "Gadgets", brand: "TriLink", price: 750, rating: 4.7, stock: true, image: "/images/products/three-in-one-cable.webp", badge: "NEW", sku: "IS-GAD-506", color: "red", description: "One durable cable with USB-C, Micro-USB and Lightning-style connectors for conveniently charging multiple everyday devices." },
  { id: 55, title: "RGB Desktop Microphone for Laptop & PC", category: "Electronics", brand: "VoiceCore", price: 1200, rating: 4.6, stock: true, image: "/images/products/desktop-microphone.webp", badge: "NEW", sku: "IS-ELC-405", color: "black", description: "A compact plug-and-play desktop microphone with flexible gooseneck, easy mute control and subtle RGB base lighting for calls and gaming." },
  { id: 56, title: "Wired In-Ear Handsfree", category: "Gadgets", brand: "SoundLine", price: 500, rating: 4.6, stock: true, image: "/images/products/wired-handsfree.webp", badge: "NEW", sku: "IS-GAD-507", color: "black", description: "Comfortable wired in-ear earphones with an inline microphone, call control and standard 3.5mm plug for music and everyday conversations." },
  { id: 57, title: "Greek Yogurt Filter & Strainer", category: "Kitchen Accessories", brand: "FreshCulture", price: 2300, oldPrice: 2700, rating: 4.8, stock: true, image: "/images/products/greek-yogurt-filter.webp", badge: "SALE", sku: "IS-KIT-109", color: "cream", description: "A reusable fine-mesh yogurt strainer with fitted container and lid for preparing thick Greek-style yogurt, labneh and soft cheese at home." },
  { id: 58, title: "Rechargeable Silicone Panda Lamp", category: "Home Decor", brand: "LumaPanda", price: 1750, oldPrice: 2450, rating: 4.9, stock: true, image: "/images/products/rechargeable-panda-lamp.webp", badge: "SALE", sku: "IS-DEC-605", color: "white", description: "A soft rechargeable reclining panda night lamp with a warm gentle glow and touch-friendly silicone body for bedrooms, nurseries and gifting." },
  { id: 59, title: "Sunset Projector Lamp with Remote", category: "Home Decor", brand: "GlowScene", price: 1500, oldPrice: 1950, rating: 4.8, stock: true, image: "/images/products/sunset-projector-lamp.webp", badge: "SALE", sku: "IS-DEC-606", color: "black", description: "An adjustable sunset projector lamp with remote control and rich multicolour ambience for bedrooms, photos, events and relaxing décor." },
  { id: 60, title: "Rechargeable High-Speed Hand Fan", category: "Gadgets", brand: "GoodDay", price: 1700, oldPrice: 2200, rating: 4.7, stock: true, image: "/images/products/rechargeable-hand-fan.webp", badge: "SALE", sku: "IS-GAD-508", color: "gold", description: "A compact rechargeable turbine hand fan with stepless speed control, clear digital display and quiet high-velocity airflow for travel and daily use." },
  { id: 61, title: "Two-Drawer Desktop Organizer", category: "Home Decor", brand: "BunnyBox", price: 950, oldPrice: 1000, rating: 4.7, stock: true, image: "/images/products/desktop-organizer.webp", badge: "NEW", sku: "IS-DEC-607", color: "pink", description: "A compact desktop storage organizer with two translucent drawers, bunny-shaped handles and an open top tray for stationery, makeup and small accessories." },
  { id: 62, title: "Canva Pro — 1 Year", category: "Digital Products", brand: "Canva", price: 700, rating: 4.9, stock: true, stockQuantity: 25, isDigital: true, image: "/images/products/digital-canva.webp", badge: "DIGITAL", sku: "IS-DIG-001", color: "blue", description: "Authorized Canva Pro subscription activation for one year. Digital fulfilment details are confirmed after payment verification." },
  { id: 63, title: "CapCut Pro — 1 Month", category: "Digital Products", brand: "CapCut", price: 1000, rating: 4.8, stock: true, stockQuantity: 25, isDigital: true, image: "/images/products/digital-capcut.webp", badge: "DIGITAL", sku: "IS-DIG-002", color: "black", description: "Authorized CapCut Pro subscription activation for one month with digital fulfilment after payment verification." },
  { id: 64, title: "ChatGPT Plus — 1 Month", category: "Digital Products", brand: "OpenAI", price: 2500, rating: 4.9, stock: true, stockQuantity: 25, isDigital: true, image: "/images/products/digital-chatgpt.webp", badge: "POPULAR", sku: "IS-DIG-003", color: "green", description: "Authorized ChatGPT Plus subscription activation for one month. Delivered digitally after payment verification." },
  { id: 65, title: "Grok Premium — 1 Month", category: "Digital Products", brand: "xAI", price: 2500, rating: 4.7, stock: true, stockQuantity: 25, isDigital: true, image: "/images/products/digital-grok.webp", badge: "DIGITAL", sku: "IS-DIG-004", color: "black", description: "Authorized Grok premium subscription activation for one month, fulfilled digitally after payment verification." },
  { id: 66, title: "Google Veo 3 Access — 1 Month", category: "Digital Products", brand: "Google", price: 4000, rating: 4.8, stock: true, stockQuantity: 25, isDigital: true, image: "/images/products/digital-veo3.webp", badge: "AI VIDEO", sku: "IS-DIG-005", color: "white", description: "Authorized Google Veo 3 access plan for one month, supplied digitally after payment verification." },
  { id: 67, title: "Google Flow Access — 1 Month", category: "Digital Products", brand: "Google", price: 4999, rating: 4.8, stock: true, stockQuantity: 25, isDigital: true, image: "/images/products/digital-flow.webp", badge: "AI VIDEO", sku: "IS-DIG-006", color: "blue", description: "Authorized Google Flow access plan for one month, supplied digitally after payment verification." },
  { id: 68, title: "Higgsfield AI — 1 Month", category: "Digital Products", brand: "Higgsfield", price: 10000, rating: 4.7, stock: true, stockQuantity: 25, isDigital: true, image: "/images/products/digital-higgsfield.webp", badge: "AI VIDEO", sku: "IS-DIG-007", color: "blue", description: "Authorized Higgsfield AI subscription activation for one month with secure digital fulfilment." },
  { id: 69, title: "Kling AI — 1 Month", category: "Digital Products", brand: "Kling AI", price: 9500, rating: 4.8, stock: true, stockQuantity: 25, isDigital: true, image: "/images/products/digital-kling.webp", badge: "AI VIDEO", sku: "IS-DIG-008", color: "black", description: "Authorized Kling AI subscription activation for one month, fulfilled digitally after payment verification." },
  { id: 70, title: "Adobe Creative Cloud — 1 Month", category: "Digital Products", brand: "Adobe", price: 4499, rating: 4.8, stock: true, stockQuantity: 25, isDigital: true, image: "/images/products/digital-adobe.webp", badge: "CREATIVE", sku: "IS-DIG-009", color: "red", description: "Authorized Adobe Creative Cloud subscription activation for one month with digital fulfilment after verification." },
  { id: 71, title: "Netflix Premium — 2 Months", category: "Digital Products", brand: "Netflix", price: 400, rating: 4.8, stock: true, stockQuantity: 25, isDigital: true, image: "/images/products/digital-netflix.webp", badge: "STREAMING", sku: "IS-DIG-010", color: "red", description: "Authorized Netflix premium subscription activation for two months. Digital delivery follows payment verification." },
  { id: 72, title: "Prime Video — 1 Month", category: "Digital Products", brand: "Prime Video", price: 250, rating: 4.7, stock: true, stockQuantity: 25, isDigital: true, image: "/images/products/digital-prime-video.webp", badge: "STREAMING", sku: "IS-DIG-011", color: "blue", description: "Authorized Prime Video subscription activation for one month. Digital delivery follows payment verification." },
];

products.forEach(product => {
  product.image = forceWebp(product.image);
  product.images = product.images?.map(forceWebp);
});

const catalogueCategories = [
  { name: "Kitchen Accessories", icon: PackageOpen, image: "/images/category-kitchen.webp" },
  { name: "Ladies & Gents Clothes", icon: Sparkles, image: "/images/category-fashion.webp" },
  { name: "Toys", icon: Gamepad2, image: "/images/category-toys.webp" },
  { name: "Electronics", icon: Monitor, image: "/images/category-electronics.webp" },
  { name: "Gadgets", icon: Smartphone, image: "/images/category-gadgets.webp" },
  { name: "Home Decor", icon: HousePlug, image: "/images/category-home-decor.webp" },
  { name: "Jewellery", icon: BadgeCheck, image: "/images/category-jewellery.webp" },
  { name: "Home Appliances", icon: Warehouse, image: "/images/category-appliances.webp" },
  { name: "Digital Products", icon: CloudDownload, image: "/images/products/digital-canva.webp" },
];

const blogPosts = [
  ["Future-ready tech", "How AI devices are changing the way we live", "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=900&q=80"],
  ["Mobile", "A practical guide to choosing your next smartphone", "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80"],
  ["Workspace", "Build a faster and calmer home office setup", "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80"],
  ["Gaming", "What really matters in a modern gaming setup", "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80"],
  ["Audio", "Find the right headphones for work and travel", "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80"],
  ["Smart Home", "Simple upgrades that make a home feel smarter", "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=900&q=80"],
] as const;

const money = (n: number) => `PKR ${n.toLocaleString("en-PK")}`;
const SHIPPING_PER_ITEM = 350;
const availableStock = (product: Product) => Math.max(0, Number(product.stockQuantity ?? (product.stock ? 10 : 0)));

export default function Storefront({ initialPath }: { initialPath: string }) {
  const [path, setPath] = useState(initialPath || "/");
  const [cart, setCart] = useState<Record<number, number>>({});
  const [wishlist, setWishlist] = useState<number[]>([]);
  const [compare, setCompare] = useState<number[]>([]);
  const [query, setQuery] = useState("");
  const [toast, setToast] = useState("");
  const [quick, setQuick] = useState<Product | null>(null);
  const [mobile, setMobile] = useState(false);
  const [, setCatalogueVersion] = useState(0);

  useEffect(() => {
    setPath(location.pathname + location.search);
    try {
      setCart(JSON.parse(localStorage.getItem("is-cart") || "{}"));
      setWishlist(JSON.parse(localStorage.getItem("is-wishlist") || "[]"));
      setCompare(JSON.parse(localStorage.getItem("is-compare") || "[]"));
    } catch {}
  }, []);
  useEffect(() => {
    fetch("/api/products", { cache:"no-store" }).then(r=>r.json()).then(data=>{
      if(Array.isArray(data.items)&&data.items.length){
        products.splice(0,products.length,...data.items.map((product: Product) => ({
          ...product,
          image: forceWebp(product.image),
          images: product.images?.map(forceWebp),
        })));
        setCatalogueVersion(v=>v+1);
      }
    }).catch(()=>{});
  }, []);
  useEffect(() => { localStorage.setItem("is-cart", JSON.stringify(cart)); }, [cart]);
  useEffect(() => { localStorage.setItem("is-wishlist", JSON.stringify(wishlist)); }, [wishlist]);
  useEffect(() => { localStorage.setItem("is-compare", JSON.stringify(compare)); }, [compare]);
  useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(""), 2600); return () => clearTimeout(t); }, [toast]);

  const go = (to: string) => { history.pushState({}, "", to); setPath(to); setMobile(false); scrollTo({ top: 0, behavior: "smooth" }); };
  useEffect(() => { const fn = () => setPath(location.pathname + location.search); addEventListener("popstate", fn); return () => removeEventListener("popstate", fn); }, []);
  const addCart = (id: number, qty = 1) => { const product=products.find(p=>p.id===id);const available=product?availableStock(product):0;setCart(c=>{const next=Math.min(available,(c[id]||0)+qty);if(next<=0)return c;return {...c,[id]:next}});setToast(available>0?"Added to cart":"This product is out of stock"); };
  const toggle = (kind: "wishlist" | "compare", id: number) => {
    const setter = kind === "wishlist" ? setWishlist : setCompare;
    setter((items: number[]) => items.includes(id) ? items.filter(x => x !== id) : [...items, id]);
    setToast(kind === "wishlist" ? "Wishlist updated" : "Comparison updated");
  };
  const cartCount = Object.values(cart).reduce((a, b) => a + b, 0);
  const suggestions = query.length > 1 ? products.filter(p => `${p.title} ${p.category} ${p.brand} ${p.sku} ${p.description}`.toLowerCase().includes(query.toLowerCase())).slice(0, 5) : [];

  return <div className="site-shell">
    <Header {...{ query, setQuery, suggestions, cartCount, wishlist, compare, go, mobile, setMobile }} />
    <main>
      {path === "/" && <Home {...{ go, addCart, toggle, setQuick, wishlist, compare }} />}
      {path.startsWith("/shop") && <Shop {...{ path, go, addCart, toggle, setQuick, wishlist, compare }} />}
      {path.startsWith("/product/") && <ProductPage product={products.find(p => path.includes(p.id.toString())) || products[0]} {...{ addCart, toggle, wishlist, compare }} />}
      {path === "/about" && <About go={go} />}
      {path === "/blog" && <Blog go={go} />}
      {path.startsWith("/blog/") && <BlogPost go={go} />}
      {path === "/contact" && <Contact setToast={setToast} />}
      {path === "/login" && <Auth mode="login" go={go} setToast={setToast} />}
      {path === "/signup" && <Auth mode="signup" go={go} setToast={setToast} />}
      {path === "/forgot-password" && <Auth mode="forgot" go={go} setToast={setToast} />}
      {path === "/staff-login" && <StaffAuth path={path} go={go} setToast={setToast}/>}
      {path.startsWith("/accept-invite") && <StaffAuth path={path} go={go} setToast={setToast}/>}
      {path === "/cart" && <Cart {...{ cart, setCart, go }} />}
      {path === "/checkout" && <Checkout {...{ cart, setCart, go, setToast }} />}
      {path.startsWith("/order-confirmation") && <OrderConfirmation path={path} go={go}/>}
      {path === "/wishlist" && <Saved title="My Wishlist" ids={wishlist} empty="Your wishlist is waiting for something special." action={id => addCart(id)} actionLabel="Move to cart" />}
      {path === "/compare" && <Compare ids={compare} addCart={addCart} />}
      {path.startsWith("/account") && <Account go={go} />}
      {path.startsWith("/admin") && <Admin setToast={setToast} />}
      {!["/", "/about", "/blog", "/contact", "/login", "/signup", "/forgot-password", "/staff-login", "/cart", "/checkout", "/wishlist", "/compare"].some(x => path === x) && !path.startsWith("/accept-invite") && !path.startsWith("/order-confirmation") && !path.startsWith("/shop") && !path.startsWith("/product/") && !path.startsWith("/blog/") && !path.startsWith("/account") && !path.startsWith("/admin") && <NotFound go={go} />}
    </main>
    {!path.startsWith("/admin") && <Footer go={go} setToast={setToast} />}
    {quick && <QuickView product={quick} close={() => setQuick(null)} addCart={addCart} />}
    {toast && <div className="toast" role="status"><Check size={18} /> {toast}</div>}
  </div>;
}

function Header(props: any) {
  const { query, setQuery, suggestions, cartCount, wishlist, compare, go, mobile, setMobile } = props;
  const nav = [["Home", "/"], ["Shop", "/shop"], ["About", "/about"], ["Blog", "/blog"], ["Contact", "/contact"]];
  return <header>
    <div className="topbar"><div className="wrap header-main">
      <button className="menu-btn" onClick={() => setMobile(!mobile)} aria-label="Open menu"><Menu /></button>
      <button className="logo-btn" onClick={() => go("/")}><img src="/insight-store-logo.webp" alt="Insight Store" /></button>
      <div className="search-wrap">
        <select aria-label="Search category"><option>All Categories</option>{catalogueCategories.map(c=><option key={c.name}>{c.name}</option>)}</select>
        <input value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === "Enter" && go(`/shop?q=${encodeURIComponent(query)}`)} placeholder="Search products, brands and categories" aria-label="Search products" />
        <button onClick={() => go(`/shop?q=${encodeURIComponent(query)}`)} aria-label="Submit search"><Search /></button>
        {suggestions.length > 0 && <div className="suggestions">{suggestions.map((p: Product) => <button key={p.id} onClick={() => { go(`/product/${p.id}`); setQuery(""); }}><img src={p.image} alt="" /><span>{p.title}<small>{money(p.price)}</small></span></button>)}</div>}
      </div>
      <div className="hotline"><span><Headset /></span><b>03145338340<small>Expert help, 24/7</small></b></div>
    </div></div>
    <div className="navrow"><div className="wrap nav-inner">
      <details className="all-cats"><summary><Grid3X3 size={18} /> All Categories</summary><div>{catalogueCategories.map(({name,icon:Icon}) => <button key={name} onClick={() => go(`/shop?category=${encodeURIComponent(name)}`)}><span><Icon size={16}/>{name}</span><ChevronRight size={16} /></button>)}</div></details>
      <nav className={mobile ? "open" : ""}>{nav.map(([n, p]) => <button key={p} onClick={() => go(p)}>{n}</button>)}</nav>
      <div className="nav-actions"><button onClick={() => go("/compare")} aria-label="Compare"><ArrowLeftRight /><i>{compare.length}</i></button><button onClick={() => go("/wishlist")} aria-label="Wishlist"><Heart /><i>{wishlist.length}</i></button><button onClick={() => go("/cart")} aria-label="Cart"><ShoppingCart /><i>{cartCount}</i></button><button className="account-link" onClick={() => go("/login")}><CircleUserRound /> Account</button></div>
    </div></div>
  </header>;
}

function Home({ go, addCart, toggle, setQuick, wishlist, compare }: any) {
  const [slide, setSlide] = useState(0);
  const [saleSeconds, setSaleSeconds] = useState((2 * 24 * 60 * 60) + (14 * 60 * 60) + (36 * 60) + 58);
  useEffect(() => { const t = setInterval(() => setSlide(s => (s + 1) % 3), 5500); return () => clearInterval(t); }, []);
  useEffect(() => {
    const t = setInterval(() => setSaleSeconds(seconds => seconds > 0 ? seconds - 1 : (2 * 24 * 60 * 60) + (14 * 60 * 60) + (36 * 60) + 58), 1000);
    return () => clearInterval(t);
  }, []);
  const saleTime = [
    { value: Math.floor(saleSeconds / 86400), label: "Days" },
    { value: Math.floor((saleSeconds % 86400) / 3600), label: "Hours" },
    { value: Math.floor((saleSeconds % 3600) / 60), label: "Minutes" },
    { value: saleSeconds % 60, label: "Seconds" },
  ];
  const bestSellers = products.filter(product => product.stock && product.rating >= 4.8).slice(0, 8);
  const slides = [
    ["HOME & KITCHEN", "Beautiful essentials for every room", "Explore kitchen accessories, home decor and reliable appliances selected for everyday living.", "/images/banner-home-living.webp", "Home Appliances"],
    ["FASHION & JEWELLERY", "Style made for every occasion", "Discover refined ladies and gents clothing with elegant jewellery to complete the look.", "/images/banner-fashion-jewellery.webp", "Ladies & Gents Clothes"],
    ["TOYS, TECH & GADGETS", "Fun meets smarter technology", "Shop playful toys, modern electronics and useful gadgets for the whole family.", "/images/banner-toys-tech.webp", "Gadgets"],
  ];
  return <>
    <section className="hero"><div className="hero-bg" style={{ backgroundImage: `linear-gradient(90deg,rgba(0,19,58,.93),rgba(0,31,86,.55),rgba(0,0,0,.08)),url('${slides[slide][3]}')` }} /><div className="wrap hero-copy"><span>{slides[slide][0]}</span><h1>{slides[slide][1]}</h1><p>{slides[slide][2]}</p><div><button className="primary" onClick={() => go("/shop")}>Shop now →</button><button className="ghost" onClick={() => go("/about")}>Explore our story</button></div></div><div className="hero-dots">{slides.map((_, i) => <button key={i} className={i === slide ? "active" : ""} onClick={() => setSlide(i)} aria-label={`Slide ${i + 1}`} />)}</div></section>
    <section className="wrap section"><SectionHead title="Shop every department" action="View all products" onClick={() => go("/shop")} /><div className="category-grid catalogue-grid">{catalogueCategories.map(({name,icon:Icon,image}) => <button key={name} onClick={() => go(`/shop?category=${encodeURIComponent(name)}`)}><span className="category-icon"><Icon/></span><img src={image} alt={name} /><b>{name}</b><small>{products.filter(p => p.category === name).length} products</small></button>)}</div></section>
    <section className="wrap promo-grid creative-promos">
      <article className="promo mint">
        <div className="promo-copy"><span><Headphones size={14}/> FEATURED</span><h3>Sound that moves with you</h3><p>Everyday audio from {money(500)}</p><button onClick={() => go("/shop?category=Gadgets")}>Shop audio <ArrowRight size={15}/></button></div>
        <div className="promo-art"><img src="/images/products/wired-handsfree.webp" alt="Wired handsfree"/><b>NEW</b></div>
      </article>
      <article className="promo blue">
        <div className="promo-copy"><span><HousePlug size={14}/> HOME EDIT</span><h3>Little lights, lovely nights</h3><p>Cosy picks to brighten your space</p><button onClick={() => go("/shop?category=Home%20Decor")}>Explore home <ArrowRight size={15}/></button></div>
        <div className="promo-art"><img src="/images/products/panda-night-lamp.webp" alt="Panda night lamp"/><b>−30%</b></div>
      </article>
      <article className="promo peach">
        <div className="promo-copy"><span><Gamepad2 size={14}/> POWER PICKS</span><h3>Level up your setup</h3><p>Fresh tech for work and play</p><button onClick={() => go("/shop?category=Electronics")}>Shop tech <ArrowRight size={15}/></button></div>
        <div className="promo-art"><img src="/images/products/desktop-microphone.webp" alt="RGB desktop microphone"/><b>HOT</b></div>
      </article>
    </section>
    <ProductSection title="Everything you need" list={products.slice(18, 26)} {...{ go, addCart, toggle, setQuick, wishlist, compare }} />
    <section className="wrap flash-sale" aria-label="Flash sale countdown">
      <div className="sale-glow sale-glow-one"/><div className="sale-glow sale-glow-two"/>
      <div className="sale-product sale-product-left"><img src="/images/products/rapid-data-cable.webp" alt=""/></div>
      <div className="sale-copy"><span><Sparkles size={13}/> FLASH SALE</span><h2>Up to 70% OFF</h2><p>Limited-time offers on selected tech & gadgets.</p><button onClick={() => go("/shop")}>Shop deals <ArrowRight size={15}/></button></div>
      <div className="sale-timer" aria-live="polite">{saleTime.map(({value,label}) => <div key={label}><b>{String(value).padStart(2, "0")}</b><small>{label}</small></div>)}</div>
      <div className="sale-product sale-product-right"><img src="/images/products/wired-handsfree.webp" alt=""/></div>
    </section>
    <ProductSection title="Best Seller" list={bestSellers} {...{ go, addCart, toggle, setQuick, wishlist, compare }} />
    <section className="wrap section"><SectionHead title="Latest from Insight" action="Read all stories" onClick={() => go("/blog")} /><div className="blog-grid home-blog">{blogPosts.slice(0, 3).map((p, i) => <BlogCard key={i} post={p} go={go} i={i} />)}</div></section>
  </>;
}

function SectionHead({ title, action, onClick }: any) { return <div className="section-head"><h2>{title}</h2><button onClick={onClick}>{action} <ArrowRight size={16}/></button></div>; }

function ProductSection(props: any) { return <section className="wrap section"><SectionHead title={props.title} action="View all" onClick={() => props.go("/shop")} /><div className="product-grid">{props.list.map((p: Product) => <ProductCard key={p.id} p={p} {...props} />)}</div></section>; }

function ProductCard({ p, go, addCart, toggle, setQuick, wishlist, compare }: any) {
  return <article className="product-card"><div className="product-image product-open" role="button" tabIndex={0} onClick={() => setQuick(p)} onKeyDown={e=>(e.key==="Enter"||e.key===" ")&&setQuick(p)} aria-label={`View ${p.title}`}>{p.badge && <em className={p.badge === "HOT" ? "hot" : ""}>{p.badge}</em>}<img src={p.image} alt={p.title} /><div className="card-actions" onClick={e=>e.stopPropagation()}><button className={wishlist.includes(p.id)?"selected":""} onClick={() => toggle("wishlist", p.id)} aria-label="Wishlist"><Heart size={17} fill={wishlist.includes(p.id)?"currentColor":"none"}/></button><button className={compare.includes(p.id)?"selected":""} onClick={() => toggle("compare", p.id)} aria-label="Compare">{compare.includes(p.id)?<Check size={17}/>:<ArrowLeftRight size={17}/>}</button><button onClick={() => setQuick(p)} aria-label="Quick view"><Eye size={17}/></button></div></div><small>{p.category}</small><button className="product-title" onClick={() => setQuick(p)}>{p.title}</button><div className="price"><b>{money(p.price)}</b>{p.oldPrice && <del>{money(p.oldPrice)}</del>}</div><div className="rating">★★★★★ <span>({p.rating})</span></div><button className="add-btn" disabled={!p.stock} onClick={() => addCart(p.id)}>{p.stock ? "Add to cart" : "Out of stock"}</button></article>;
}

function Shop({ path, go, addCart, toggle, setQuick, wishlist, compare }: any) {
  const params = new URLSearchParams(path.split("?")[1] || "");
  const [search, setSearch] = useState(params.get("q") || "");
  const [category, setCategory] = useState(params.get("category") || "All");
  const [brand, setBrand] = useState("All");
  const [max, setMax] = useState(250000);
  const [sort, setSort] = useState("popular");
  const [filters, setFilters] = useState(false);
  const list = useMemo(() => {
    let r = products.filter(p => p.price <= max && (category === "All" || p.category.toLowerCase().includes(category.toLowerCase())) && (brand === "All" || p.brand === brand) && `${p.title} ${p.category} ${p.brand}`.toLowerCase().includes(search.toLowerCase()));
    if (sort === "low") r.sort((a,b) => a.price-b.price); if (sort === "high") r.sort((a,b) => b.price-a.price); if (sort === "rated") r.sort((a,b) => b.rating-a.rating); return r;
  }, [search, category, brand, max, sort]);
  const side = <aside className={filters ? "filters open" : "filters"}><button className="filter-close icon-button" aria-label="Close filters" onClick={() => setFilters(false)}><X /></button><h3>Filter products</h3><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search products" /><label>Price up to <b>{money(max)}</b><input type="range" min="8000" max="250000" step="1000" value={max} onChange={e => setMax(+e.target.value)} /></label><h4>Categories</h4>{["All", ...new Set(products.map(p => p.category))].map(c => <label className="check" key={c}><input type="radio" name="cat" checked={category === c} onChange={() => setCategory(c)} /> {c}</label>)}<h4>Brands</h4><select value={brand} onChange={e => setBrand(e.target.value)}><option>All</option>{[...new Set(products.map(p => p.brand))].map(b => <option key={b}>{b}</option>)}</select><h4>Availability</h4><label className="check"><input type="checkbox" /> In stock</label><label className="check"><input type="checkbox" /> On sale</label><button className="clear" onClick={() => { setSearch(""); setCategory("All"); setBrand("All"); setMax(250000); }}>Clear filters</button></aside>;
  return <div className="wrap page"><Breadcrumb items={["Home", "Shop"]} /><div className="shop-layout">{side}<section className="shop-results"><div className="shop-toolbar"><span>Showing <b>{list.length}</b> products</span><button className="filter-open" onClick={() => setFilters(true)}><SlidersHorizontal size={17}/> Filters</button><select value={sort} onChange={e => setSort(e.target.value)}><option value="popular">Most popular</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="rated">Best rated</option></select></div>{list.length ? <div className="product-grid shop-grid">{list.map(p => <ProductCard key={p.id} p={p} {...{ go, addCart, toggle, setQuick, wishlist, compare }} />)}</div> : <Empty title="No products found" text="Try clearing a filter or searching for something broader." />}<div className="pagination"><button aria-label="Previous page"><ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><button aria-label="Next page"><ChevronRight/></button></div></section></div></div>;
}

function ProductPage({ product: p, addCart, toggle, wishlist, compare }: any) {
  const [qty, setQty] = useState(1); const [tab, setTab] = useState("Description");
  return <div className="wrap page"><Breadcrumb items={["Home", "Shop", p.title]} /><section className="product-detail"><div className="detail-image"><img src={p.image} alt={p.title} /><span>Hover to view details</span></div><div className="detail-copy"><small>{p.category} · {p.brand}</small><h1>{p.title}</h1><div className="rating">★★★★★ <span>{p.rating} · 128 verified reviews</span></div><div className="detail-price">{money(p.price)} {p.oldPrice && <del>{money(p.oldPrice)}</del>}</div><p>{p.description}</p><dl><div><dt>SKU</dt><dd>{p.sku}</dd></div><div><dt>Availability</dt><dd className={p.stock ? "green" : "red"}>{p.stock ? "In stock" : "Out of stock"}</dd></div><div><dt>Delivery</dt><dd>2–4 business days</dd></div></dl><label className="option">Color <select><option>{p.color}</option><option>midnight</option></select></label><div className="buy-row"><div className="qty"><button onClick={() => setQty(Math.max(1, qty - 1))}>−</button><b>{qty}</b><button onClick={() => setQty(qty + 1)}>+</button></div><button className="primary" onClick={() => addCart(p.id, qty)}>Add to cart</button></div><div className="secondary-actions"><button onClick={() => toggle("wishlist", p.id)}>{wishlist.includes(p.id) ? "♥ Saved" : "♡ Add to wishlist"}</button><button onClick={() => toggle("compare", p.id)}>{compare.includes(p.id) ? "✓ Comparing" : "⇄ Compare"}</button></div></div></section><section className="tabs"><div>{["Description", "Specifications", "Reviews"].map(t => <button className={tab === t ? "active" : ""} key={t} onClick={() => setTab(t)}>{t}</button>)}</div>{tab === "Description" && <p>{p.description} Every item from Insight Store is quality checked, carefully packed and backed by responsive local support.</p>}{tab === "Specifications" && <table><tbody><tr><th>Brand</th><td>{p.brand}</td></tr><tr><th>Category</th><td>{p.category}</td></tr><tr><th>Color</th><td>{p.color}</td></tr><tr><th>Warranty</th><td>1 year official warranty</td></tr></tbody></table>}{tab === "Reviews" && <p>Rated {p.rating}/5 by verified customers. Sign in after purchase to leave a review.</p>}</section></div>;
}

function About({ go }: any) { return <div className="page"><div className="wrap"><Breadcrumb items={["Home", "About Us"]} /><section className="about-top"><div className="about-images"><img src="https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=85" alt="Insight Store team" /><b>12<small>years of<br/>experience</small></b></div><div><span className="eyebrow">ABOUT INSIGHT STORE</span><h1>Technology that makes everyday life feel more possible.</h1><p>Insight Store is a customer-first electronics destination for carefully selected devices, honest guidance and dependable after-sales support.</p><p>From smartphones and computers to smart homes and gaming, every product is selected for performance, value and lasting usefulness.</p><div className="stats"><b>25+<small>Retail partners</small></b><b>3k+<small>Monthly deliveries</small></b><b>120+<small>Trusted brands</small></b></div></div></section></div><section className="watch-banner"><div className="wrap"><span>CURATED LUXURY</span><h2>Time, beautifully engineered.</h2><button className="primary" onClick={() => go("/shop?category=Wearables")}>Shop watches</button></div></section><section className="wrap section"><SectionHead title="Loved by customers" action="Shop with confidence" onClick={() => go("/shop")} /><div className="testimonials">{["Fast delivery and the packaging was excellent.", "The team helped me choose the right laptop without upselling.", "A genuinely smooth checkout and after-sales experience."].map((t, i) => <article key={t}><div className="rating">★★★★★</div><p>“{t}”</p><b>{["Areeba Khan", "Hamza Ali", "Sara Ahmed"][i]}</b><small>Verified customer</small></article>)}</div></section></div>; }

function Blog({ go }: any) { return <div className="wrap page"><Breadcrumb items={["Home", "Blog"]} /><h1 className="page-title">Ideas, guides & inspiration</h1><div className="blog-layout"><section className="blog-grid">{blogPosts.concat(blogPosts).map((p, i) => <BlogCard key={i} post={p} go={go} i={i} />)}</section><aside className="blog-side"><input placeholder="Search stories" /><h3>Categories</h3>{["Buying guides", "Mobile", "Smart home", "Gaming", "Audio"].map(x => <button key={x}>{x}<span>›</span></button>)}<div className="side-ad"><span>EDITOR'S PICK</span><h3>Make your setup work smarter.</h3><button onClick={() => go("/shop")}>Shop now</button></div><h3>Popular tags</h3><div className="tags">{["Innovation", "Reviews", "Guides", "Workspace", "Mobile"].map(x => <button key={x}>{x}</button>)}</div></aside></div></div>; }
function BlogCard({ post, go, i }: any) { return <article className="blog-card"><button onClick={() => go(`/blog/${i + 1}`)}><img src={post[2]} alt="" /></button><small>{post[0]} · Insight Editorial</small><h3><button onClick={() => go(`/blog/${i + 1}`)}>{post[1]}</button></h3><p>Clear advice and useful ideas to help you get more from the technology around you.</p></article>; }
function BlogPost({ go }: any) { return <article className="wrap article page"><Breadcrumb items={["Home", "Blog", "How AI devices are changing the way we live"]} /><span className="eyebrow">FUTURE-READY TECH</span><h1>How AI devices are changing the way we live</h1><p className="lead">Smarter products are moving from novelty to genuinely useful companions. Here is what to look for—and what to ignore.</p><img className="article-hero" src={blogPosts[0][2]} alt="AI-powered home technology" /><p>Useful technology earns its place quietly. The best new devices reduce friction, learn sensible preferences and keep people in control. That matters more than a long list of impressive-sounding features.</p><h2>Start with the problem, not the specification</h2><p>Choose products around a real routine: a laptop that stays responsive through a workday, headphones that make calls clearer, or a smart-home system that simplifies repetitive tasks. A focused product usually outperforms a complicated one.</p><blockquote>Good technology should create time and confidence—not another thing to manage.</blockquote><p>At Insight Store, our buying guides combine hands-on evaluation with practical ownership advice so you can compare the details that actually change the experience.</p><button className="primary" onClick={() => go("/blog")}>← Back to all stories</button></article>; }

function Contact({ setToast }: any) { const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); try { await fetch("/api/messages", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data) }); } catch {} e.currentTarget.reset(); setToast("Message sent — we'll be in touch shortly"); }; const cards=[[MapPin,"Corporate Office","Wahdat Colony, Taxila"],[Warehouse,"Main Warehouse","Model Town Phase 1"],[Mail,"Email Address","hello@insightstore.pk"],[Phone,"Phone Number","03145338340"]] as const; return <div className="wrap page"><Breadcrumb items={["Home", "Contact"]} /><h1 className="page-title">Contact Information</h1><div className="contact-cards">{cards.map(([Icon,title,text]) => <article key={title}><i><Icon/></i><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><div className="contact-main"><form onSubmit={submit}><div><label>Name<input required name="name" /></label><label>Email<input required type="email" name="email" /></label></div><div><label>Phone<input name="phone" /></label><label>Subject<input required name="subject" /></label></div><label>Write message<textarea required name="message" rows={6} /></label><button className="primary">Send message</button></form><div className="map"><iframe title="Map of Wahdat Colony, Taxila" src="https://www.openstreetmap.org/export/embed.html?bbox=72.78742%2C33.71499%2C72.81742%2C33.73499&amp;layer=mapnik&amp;marker=33.72499%2C72.80242" loading="lazy"/><div className="map-panel"><MapPin size={24}/><span>INSIGHT STORE TAXILA</span><strong>Wahdat Colony, Taxila</strong><small>33.72499° N · 72.80242° E</small><a href="https://www.openstreetmap.org/?mlat=33.72499&amp;mlon=72.80242#map=15/33.72499/72.80242" target="_blank" rel="noreferrer">Open interactive map <ArrowRight size={16}/></a></div></div></div></div>; }

function Auth({ mode, go, setToast }: any) { const signup = mode === "signup", forgot = mode === "forgot"; const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setToast(forgot ? "Reset link sent" : signup ? "Account created — check your email" : "Welcome back"); go(forgot || signup ? "/login" : "/account"); }; return <div className="wrap page auth-page"><Breadcrumb items={["Home", forgot ? "Forgot Password" : signup ? "Signup" : "Login"]} /><h1>{forgot ? "Reset your password" : signup ? "Create your account" : "Login to your account"}</h1><form onSubmit={submit} className="auth-card">{signup && <><label>Full name<input required name="name" /></label><label>Phone<input required name="phone" /></label></>}<label>Email<input required type="email" name="email" /></label>{!forgot && <label>Password<input required minLength={8} type="password" name="password" /></label>}<button className="primary">{forgot ? "Send reset link" : signup ? "Sign up" : "Log in"}</button>{!forgot && <><div className="or">or continue with</div><button type="button" className="social" onClick={() => setToast("Google sign-in requires provider credentials")}>G &nbsp; Google</button><button type="button" className="social" onClick={() => setToast("Facebook sign-in requires provider credentials")}>f &nbsp; Facebook</button><label className="remember"><input type="checkbox" /> Remember me</label></>}<p>{forgot ? <button type="button" onClick={() => go("/login")}>Back to login</button> : signup ? <>Already have an account? <button type="button" onClick={() => go("/login")}>Login here</button></> : <>New here? <button type="button" onClick={() => go("/signup")}>Create an account</button> · <button type="button" onClick={() => go("/forgot-password")}>Forgot password?</button></>}</p></form></div>; }

function StaffAuth({path,go,setToast}:any){
  const token=new URLSearchParams(path.split("?")[1]||"").get("token")||"";
  const accepting=!!token;const [busy,setBusy]=useState(false);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const form=new FormData(e.currentTarget);try{const response=await fetch("/api/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(accepting?{action:"accept-invite",token,name:form.get("name"),password:form.get("password")}:{action:"login",email:form.get("email"),password:form.get("password")})});const data=await response.json();if(!response.ok)throw new Error(data.error);setToast(accepting?"Editor account activated":"Staff login successful");go(data.user?.role==="editor"?"/admin":"/admin")}catch(error:any){setToast(error.message)}finally{setBusy(false)}};
  return <div className="wrap page auth-page"><Breadcrumb items={["Home",accepting?"Accept invitation":"Staff login"]}/><h1>{accepting?"Activate your editor account":"Admin & editor login"}</h1><form className="auth-card" onSubmit={submit}>{accepting?<label>Full name<input name="name" required/></label>:<label>Staff email<input name="email" type="email" required/></label>}<label>Password<input name="password" type="password" minLength={8} required/></label><button className="primary" disabled={busy}>{busy?"Please wait…":accepting?"Activate editor account":"Log in to dashboard"}</button><p>This login is only for authorized Insight Store staff.</p></form></div>
}

function Cart({ cart, setCart, go }: any) { const items = products.filter(p => cart[p.id]); const subtotal = items.reduce((s, p) => s + p.price * cart[p.id], 0); const physicalItemCount=items.filter(p=>!p.isDigital).reduce((count,p)=>count+cart[p.id],0); return <div className="wrap page"><Breadcrumb items={["Home", "Cart"]} /><h1 className="page-title">Your cart</h1>{items.length ? <div className="cart-layout"><div>{items.map(p => <article className="cart-item" key={p.id}><img src={p.image} alt="" /><div><h3>{p.title}</h3><small>{p.sku}{p.isDigital?" · Digital delivery":""}</small><b>{money(p.price)}</b><small>{p.stockQuantity??0} available</small></div><div className="qty"><button onClick={() => setCart((c: any) => ({ ...c, [p.id]: Math.max(1, c[p.id]-1) }))}>−</button><b>{cart[p.id]}</b><button disabled={cart[p.id]>=Number(p.stockQuantity??0)} onClick={() => setCart((c: any) => ({ ...c, [p.id]: Math.min(Number(p.stockQuantity??0),c[p.id]+1) }))}>+</button></div><button className="remove" onClick={() => setCart((c: any) => { const n={...c}; delete n[p.id]; return n; })}>Remove</button></article>)}</div><OrderBox subtotal={subtotal} physicalItemCount={physicalItemCount} checkout={() => go("/checkout")} /></div> : <Empty title="Your cart is empty" text="Great products are only a click away." action={() => go("/shop")} />}</div>; }
function OrderBox({ subtotal, physicalItemCount, checkout }: any) { const shipping = physicalItemCount * SHIPPING_PER_ITEM; const tax = Math.round(subtotal * .02); return <aside className="order-box"><h3>Order summary</h3><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>{physicalItemCount?`Shipping (${physicalItemCount} × ${money(SHIPPING_PER_ITEM)})`:"Digital delivery"}</span><b>{shipping?money(shipping):"Free"}</b></div><div><span>Tax estimate</span><b>{money(tax)}</b></div><div className="total"><span>Total</span><b>{money(subtotal+shipping+tax)}</b></div><input placeholder="Coupon code" /><button className="primary" onClick={checkout}>Proceed to checkout</button></aside>; }
function Checkout({ cart, setCart, go, setToast }: any) {
  const items=products.filter(p=>cart[p.id]);const subtotal=items.reduce((s,p)=>s+p.price*cart[p.id],0);const physicalItemCount=items.filter(p=>!p.isDigital).reduce((count,p)=>count+cart[p.id],0);const shipping=physicalItemCount*SHIPPING_PER_ITEM,tax=Math.round(subtotal*.02),total=subtotal+shipping+tax;
  const [settings,setSettings]=useState<any>({payment_method_name:"Easypaisa",account_holder_name:"Insight Store",easypaisa_number:"03145338340",payment_instructions:"Send the exact total, then upload your screenshot."});
  const [proof,setProof]=useState<any>(null);const [uploading,setUploading]=useState(false);const [submitting,setSubmitting]=useState(false);const [idempotencyKey]=useState(()=>crypto.randomUUID());
  useEffect(()=>{fetch("/api/payment-settings",{cache:"no-store"}).then(r=>r.json()).then(setSettings).catch(()=>{})},[]);
  const upload=async(file?:File)=>{if(!file)return;setUploading(true);try{const body=new FormData();body.append("file",file);body.append("kind","payment-proof");const response=await fetch("/api/media",{method:"POST",body});const data=await response.json();if(!response.ok)throw new Error(data.error);setProof(data)}catch(e:any){setToast(e.message)}finally{setUploading(false)}};
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!proof){setToast("Upload your payment screenshot first");return}setSubmitting(true);const f=new FormData(e.currentTarget);try{const response=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({idempotency_key:idempotencyKey,customer_name:`${f.get("first_name")} ${f.get("last_name")}`.trim(),email:f.get("email"),phone:f.get("phone"),city:f.get("city"),postal_code:f.get("postal_code"),address:f.get("address"),transaction_reference:f.get("transaction_reference"),proof_url:proof.url,items:items.map(p=>({id:p.id,quantity:cart[p.id]}))})});const data=await response.json();if(!response.ok)throw new Error(data.error);if(!data.completed)throw new Error("Order confirmation was not completed.");setCart({});go(`/order-confirmation?order=${encodeURIComponent(data.order_number)}&token=${encodeURIComponent(data.access_token)}`)}catch(e:any){setToast(e.message)}finally{setSubmitting(false)}};
  return <div className="wrap page"><Breadcrumb items={["Home","Cart","Checkout"]}/><h1 className="page-title">Checkout & payment proof</h1>{!items.length?<Empty title="Nothing to check out" text="Add a product to your cart first." action={()=>go("/shop")}/>:<form className="checkout manual-checkout" onSubmit={submit}><section><h2>Billing & delivery</h2><div className="form-grid"><label>First name<input required name="first_name"/></label><label>Last name<input required name="last_name"/></label><label>Email<input required type="email" name="email"/></label><label>Phone<input required name="phone"/></label><label>City<input required name="city"/></label><label>Postal code<input name="postal_code"/></label></div><label>Delivery address<textarea required name="address" rows={3}/></label><h2>Manual payment</h2><div className="easypaisa-box"><span>{settings.payment_method_name}</span><b>{settings.easypaisa_number}</b><small>{settings.account_holder_name}</small><button type="button" onClick={()=>{navigator.clipboard.writeText(settings.easypaisa_number);setToast("Easypaisa number copied")}}><Copy size={16}/> Copy number</button><p>{settings.payment_instructions}</p><strong>Send exactly {money(total)}</strong></div><label>Transaction ID / Reference number <small>(optional)</small><input name="transaction_reference" autoComplete="off" placeholder="Enter it if available"/></label><label className="proof-uploader">{proof?<img src={proof.url} alt="Payment proof preview"/>:<UploadCloud/>}<b>{proof?proof.name:"Upload payment screenshot"}</b><span>{uploading?"Uploading…":"Browse from device or drag & drop"}</span><input type="file" required={!proof} accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])}/>{proof&&<button type="button" onClick={()=>setProof(null)}>Replace screenshot</button>}</label></section><aside className="order-box checkout-summary"><h3>Order summary</h3>{items.map(p=><div className="checkout-line" key={p.id}><img src={p.image} alt=""/><span><b>{p.title}</b><small>{cart[p.id]} × {money(p.price)}{p.isDigital?" · Digital":""}</small></span></div>)}<div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>{physicalItemCount?`Shipping (${physicalItemCount} × ${money(SHIPPING_PER_ITEM)})`:"Digital delivery"}</span><b>{shipping?money(shipping):"Free"}</b></div><div><span>Tax estimate</span><b>{money(tax)}</b></div><div className="total"><span>Total</span><b>{money(total)}</b></div><button className="primary" disabled={submitting||uploading}>{submitting?"Submitting…":"Submit payment proof"}</button><small className="verification-note">Your order will only be confirmed after manual payment verification.</small></aside></form>}</div>;
}
function OrderConfirmation({path,go}:any){const params=new URLSearchParams(path.split("?")[1]||""),number=params.get("order")||"",token=params.get("token")||"";const [data,setData]=useState<any>(null);useEffect(()=>{if(number&&token)fetch(`/api/orders?order_number=${encodeURIComponent(number)}&token=${encodeURIComponent(token)}`,{cache:"no-store"}).then(r=>r.json()).then(setData)},[number,token]);return <div className="wrap page"><div className="confirmation-card"><CheckCircle2/><span>{data?.order?.payment_status==="Paid"?"PAYMENT APPROVED":"PAYMENT SCREENSHOT RECEIVED"}</span><h1>{data?"Thanks for your order":"Confirming your order…"}</h1><p>{data?.order?.payment_status==="Paid"?"Your payment has been approved and your order is confirmed.":"Your order is saved, its stock has been reserved, and your payment is awaiting verification."}</p><div><b>{number}</b><span>{data?.order?.payment_status||"Verification Pending"}</span></div><button className="primary" onClick={()=>go("/shop")}>Continue shopping</button></div></div>}

function Saved({ title, ids, empty, action, actionLabel }: any) { const list=products.filter(p=>ids.includes(p.id)); return <div className="wrap page"><Breadcrumb items={["Home", title]} /><h1 className="page-title">{title}</h1>{list.length?<div className="saved-grid">{list.map(p=><article key={p.id}><img src={p.image} alt=""/><div><small>{p.category}</small><h3>{p.title}</h3><b>{money(p.price)}</b></div><button className="primary" onClick={()=>action(p.id)}>{actionLabel}</button></article>)}</div>:<Empty title={`No items in ${title.toLowerCase()}`} text={empty}/>}</div>; }
function Compare({ ids, addCart }: any) { const list=products.filter(p=>ids.includes(p.id)); return <div className="wrap page"><Breadcrumb items={["Home","Compare"]}/><h1 className="page-title">Compare products</h1>{list.length?<div className="compare-table"><table><thead><tr><th>Feature</th>{list.map(p=><th key={p.id}><img src={p.image} alt=""/><b>{p.title}</b></th>)}</tr></thead><tbody>{[["Price",(p:Product)=>money(p.price)],["Brand",(p:Product)=>p.brand],["Rating",(p:Product)=>`${p.rating}/5`],["Stock",(p:Product)=>p.stock?"In stock":"Out of stock"]].map(([n,fn]:any)=><tr key={n}><th>{n}</th>{list.map(p=><td key={p.id}>{fn(p)}</td>)}</tr>)}<tr><th>Action</th>{list.map(p=><td key={p.id}><button className="primary" onClick={()=>addCart(p.id)}>Add to cart</button></td>)}</tr></tbody></table></div>:<Empty title="Nothing to compare yet" text="Add products from the shop to see them side by side."/>}</div>; }

function Account({ go }: any) { return <div className="wrap page account"><aside><h3>My account</h3>{[["Overview","/account"],["Orders","/account/orders"],["Profile","/account/profile"],["Addresses","/account/addresses"],["Wishlist","/wishlist"]].map(x=><button key={x[0]} onClick={()=>go(x[1])}>{x[0]}<span>›</span></button>)}<button onClick={()=>go("/")}>Log out</button></aside><section><span className="eyebrow">WELCOME BACK</span><h1>Account overview</h1><div className="account-stats"><article><b>3</b><span>Total orders</span></article><article><b>1</b><span>In progress</span></article><article><b>{money(252997)}</b><span>Total spent</span></article></div><h2>Recent orders</h2><div className="order-row"><b>#IS-10428</b><span>12 Aug 2026</span><span className="pill">Processing</span><b>{money(92999)}</b></div><div className="order-row"><b>#IS-10387</b><span>29 Jul 2026</span><span className="pill delivered">Delivered</span><b>{money(24999)}</b></div></section></div>; }

function Admin({ setToast }: any) { const [state,setState]=useState<any>(null);useEffect(()=>{fetch("/api/auth",{cache:"no-store"}).then(async r=>({ok:r.ok,data:await r.json()})).then(x=>setState(x.ok?x.data.user:false)).catch(()=>setState(false))},[]);if(state===null)return <div className="admin-state">Checking staff access…</div>;if(state===false)return <div className="wrap page auth-page"><h1>Staff access required</h1><div className="auth-card"><p>Log in with an active admin or editor account to open this dashboard.</p><a className="primary" href="/staff-login">Open staff login</a></div></div>;return <AdminPanel seedProducts={products} setToast={setToast}/>; }

function QuickView({ product:p, close, addCart }: any) {
  const [qty,setQty]=useState(1);
  const [active,setActive]=useState(0);
  const media=(p.images?.filter(Boolean)?.length?p.images:[p.image,p.image,p.image]).slice(0,3);
  return <div className="modal-backdrop product-popup-backdrop" onMouseDown={close}><div className="quick-modal product-popup" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-label={p.title}><button className="modal-close icon-button" aria-label="Close product" onClick={close}><X/></button><div className="popup-gallery"><div className="popup-main-media">{p.videoUrl&&active===media.length?<video src={p.videoUrl} controls playsInline/>:<img src={media[active]||p.image} alt={p.title}/>}</div><div className="popup-thumbs">{media.map((src:string,i:number)=><button key={i} className={active===i?"active":""} onClick={()=>setActive(i)}><img src={src} alt={`${p.title} view ${i+1}`}/></button>)}{p.videoUrl&&<button className={active===media.length?"active video-thumb": "video-thumb"} onClick={()=>setActive(media.length)}>▶<span>Video</span></button>}</div></div><div className="popup-copy"><small>{p.category} · {p.brand}</small><h2>{p.title}</h2><div className="rating">★★★★★ <span>{p.rating} verified rating</span></div><div className="detail-price">{money(p.price)} {p.oldPrice&&<del>{money(p.oldPrice)}</del>}</div><p>{p.description}</p><dl><div><dt>SKU</dt><dd>{p.sku}</dd></div><div><dt>Availability</dt><dd className={p.stock?"green":"red"}>{p.stock?"In stock":"Out of stock"}</dd></div><div><dt>Delivery</dt><dd>2–4 business days</dd></div></dl><div className="buy-row"><div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))}>−</button><b>{qty}</b><button onClick={()=>setQty(qty+1)}>+</button></div><button className="primary" onClick={()=>addCart(p.id,qty)}>Add to cart</button></div><div className="popup-actions"><button onClick={close}>Continue shopping</button><button className="primary" onClick={()=>{addCart(p.id,qty);close();location.href="/cart"}}>View cart</button></div></div></div></div>;
}
function Breadcrumb({items}:any){return <div className="breadcrumb">{items.map((x:string,i:number)=><span key={x}>{i>0&&" / "}{x}</span>)}</div>}
function Empty({title,text,action}:any){return <div className="empty"><div><PackageOpen/></div><h2>{title}</h2><p>{text}</p>{action&&<button className="primary" onClick={action}>Browse products <ArrowRight size={17}/></button>}</div>}
function NotFound({go}:any){return <div className="not-found"><div className="lost-mark">4<span><Search/></span>4</div><h1>Oops! That page can not be found.</h1><p>The page may have moved, but the best of Insight Store is still right here.</p><button onClick={()=>history.back()}><ArrowLeft size={17}/> Go back</button><button className="primary" onClick={()=>go("/")}>Go to homepage</button></div>}

function Footer({go,setToast}:any){const subscribe=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const email=new FormData(e.currentTarget).get("email");try{await fetch("/api/newsletter",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});}catch{}e.currentTarget.reset();setToast("You're on the Insight list");};const benefits=[[Truck,"Same-day delivery"],[CreditCard,"Secure payments"],[Headset,"Expert guidance"],[ShieldCheck,"Official warranty"],[Phone,"24/7 support"]] as const;return <footer><div className="benefits"><div className="wrap">{benefits.map(([Icon,label])=><div key={label}><i><Icon/></i><b>{label}</b></div>)}</div></div><div className="footer-main"><div className="wrap footer-grid"><div className="footer-brand"><img src="/insight-store-logo.webp" alt="Insight Store"/><a className="footer-phone" href="tel:+923145338340">03145338340</a><p><span>Wahdat Colony, Taxila</span><a href="mailto:hello@insightstore.pk">hello@insightstore.pk</a></p><div className="social-icons"><a href="#" aria-label="Facebook"><Facebook/></a><a href="#" aria-label="Instagram"><Instagram/></a><a href="#" aria-label="LinkedIn"><Linkedin/></a><a href="#" aria-label="YouTube"><Youtube/></a></div></div>{[["Resources",[["About Us","/about"],["Shop","/shop"],["Cart","/cart"],["Brands","/shop"]]],["Support",[["Contact","/contact"],["Returns","/about"],["My account","/account"],["Wishlist","/wishlist"]]],["Store info",[["Best sellers","/shop"],["New arrivals","/shop"],["Compare","/compare"],["Admin","/admin"]]]].map(([h,links]:any)=><div className="footer-links" key={h}><h3>{h}</h3>{links.map((x:any)=><button key={x[0]} onClick={()=>go(x[1])}>{x[0]}</button>)}</div>)}<div className="newsletter"><h3>Stay in the know</h3><p>New tech, useful guides and members-only offers.</p><form onSubmit={subscribe}><input required type="email" name="email" autoComplete="email" placeholder="Enter your email address"/><button aria-label="Subscribe"><ArrowRight/></button></form><small>Useful updates only. No spam.</small></div></div><div className="wrap footer-bottom"><span>© 2026 Insight Store. All rights reserved.</span><b>VISA &nbsp; Mastercard &nbsp; COD &nbsp; Bank Transfer</b></div></div></footer>}

