import { env } from "cloudflare:workers";

function clean(value:unknown,max=500){return String(value||"").trim().slice(0,max)}

async function schema(){
  await env.DB.batch([
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS store_orders (id INTEGER PRIMARY KEY AUTOINCREMENT, order_number TEXT NOT NULL UNIQUE, access_token TEXT, idempotency_key TEXT UNIQUE, customer_name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT NOT NULL, city TEXT NOT NULL, postal_code TEXT, address TEXT NOT NULL, subtotal REAL NOT NULL, shipping REAL NOT NULL, tax REAL NOT NULL, total REAL NOT NULL, payment_method TEXT NOT NULL, payment_status TEXT NOT NULL, order_status TEXT NOT NULL, transaction_reference TEXT NOT NULL, proof_url TEXT NOT NULL, admin_note TEXT, verified_by TEXT, verified_at INTEGER, inventory_deducted_at INTEGER, inventory_restored_at INTEGER, reservation_expires_at INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS order_items (id INTEGER PRIMARY KEY AUTOINCREMENT, order_id INTEGER NOT NULL, product_id INTEGER NOT NULL, title TEXT NOT NULL, sku TEXT NOT NULL, quantity INTEGER NOT NULL, unit_price REAL NOT NULL, image TEXT, FOREIGN KEY(order_id) REFERENCES store_orders(id))`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS inventory_movements (id INTEGER PRIMARY KEY AUTOINCREMENT, product_id INTEGER NOT NULL, order_id INTEGER, actor_user_id TEXT, movement_type TEXT NOT NULL, quantity_change INTEGER NOT NULL, quantity_before INTEGER NOT NULL, quantity_after INTEGER NOT NULL, reason TEXT NOT NULL, idempotency_key TEXT UNIQUE, created_at INTEGER NOT NULL)`),
    env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_store_orders_status_created ON store_orders(payment_status,created_at)"),
    env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_inventory_product_created ON inventory_movements(product_id,created_at)"),
    env.DB.prepare(`CREATE TRIGGER IF NOT EXISTS prevent_negative_product_stock BEFORE UPDATE OF stock_quantity ON catalog_products WHEN NEW.stock_quantity < 0 BEGIN SELECT RAISE(ABORT,'INSUFFICIENT_STOCK'); END`),
  ]);
  for(const statement of ["ALTER TABLE store_orders ADD COLUMN access_token TEXT","ALTER TABLE store_orders ADD COLUMN idempotency_key TEXT","ALTER TABLE store_orders ADD COLUMN inventory_deducted_at INTEGER","ALTER TABLE store_orders ADD COLUMN inventory_restored_at INTEGER","ALTER TABLE store_orders ADD COLUMN reservation_expires_at INTEGER"]){try{await env.DB.prepare(statement).run()}catch{}}
  try{await env.DB.prepare("CREATE UNIQUE INDEX IF NOT EXISTS idx_store_orders_idempotency ON store_orders(idempotency_key)").run()}catch{}
}

export async function POST(request:Request){
  await schema();const body=await request.json() as any;const idempotencyKey=clean(body.idempotency_key,100);
  if(!idempotencyKey)return Response.json({error:"Checkout session expired. Refresh checkout and try again."},{status:400});
  const repeated=await env.DB.prepare("SELECT * FROM store_orders WHERE idempotency_key=?").bind(idempotencyKey).first<any>();
  if(repeated)return Response.json({order_id:repeated.id,order_number:repeated.order_number,access_token:repeated.access_token,total:repeated.total,payment_status:repeated.payment_status,order_status:repeated.order_status,completed:true});
  if(!Array.isArray(body.items)||!body.items.length)return Response.json({error:"Your cart is empty."},{status:400});
  const ids=body.items.map((x:any)=>Number(x.id)).filter(Number.isFinite);if(ids.length!==body.items.length)return Response.json({error:"Invalid cart."},{status:400});
  const result=await env.DB.prepare(`SELECT * FROM catalog_products WHERE id IN (${ids.map(()=>"?").join(",")}) AND status='active'`).bind(...ids).all<any>();
  const byId=new Map(result.results.map((p:any)=>[Number(p.id),p]));const items=body.items.map((x:any)=>({p:byId.get(Number(x.id)),qty:Math.max(1,Math.min(99,Math.floor(Number(x.quantity)||1)))}));
  if(items.some((x:any)=>!x.p))return Response.json({error:"One or more products are unavailable. Refresh your cart."},{status:409});
  const shortage=items.find((x:any)=>x.qty>Number(x.p.stock_quantity));if(shortage)return Response.json({error:`${shortage.p.title} has only ${shortage.p.stock_quantity} available. Update your cart.`,product_id:shortage.p.id,available:Number(shortage.p.stock_quantity)},{status:409});
  const proof=clean(body.proof_url,700);if(!proof.startsWith("/api/media/payment-proofs/"))return Response.json({error:"Payment screenshot is required."},{status:400});
  const proofKey=decodeURIComponent(proof.slice("/api/media/".length));let proofAsset:any=null;try{proofAsset=await env.DB.prepare("SELECT id FROM media_assets WHERE object_key=? AND kind='payment-proof'").bind(proofKey).first()}catch{}if(!proofAsset)return Response.json({error:"Upload a valid payment screenshot before completing checkout."},{status:400});
  for(const field of ["customer_name","email","phone","city","address"])if(!clean(body[field]))return Response.json({error:"Complete all required customer details."},{status:400});
  const transaction=clean(body.transaction_reference,100);if(transaction){const existing=await env.DB.prepare("SELECT id FROM store_orders WHERE transaction_reference=?").bind(transaction).first();if(existing)return Response.json({error:"This transaction ID has already been submitted."},{status:409})}
  const subtotal=items.reduce((sum:number,x:any)=>sum+Number(x.p.price)*x.qty,0),physicalItemCount=items.filter((x:any)=>!Number(x.p.is_digital)).reduce((count:number,x:any)=>count+x.qty,0),shipping=physicalItemCount*350,tax=Math.round(subtotal*.02),total=subtotal+shipping+tax;
  const now=Date.now(),orderId=now*1000+Math.floor(Math.random()*1000),number=`IS-${String(now).slice(-7)}${String(orderId).slice(-2)}`,accessToken=crypto.randomUUID(),storedReference=transaction||`optional-${number}`;
  const statements:any[]=[env.DB.prepare(`INSERT INTO store_orders (id,order_number,access_token,idempotency_key,customer_name,email,phone,city,postal_code,address,subtotal,shipping,tax,total,payment_method,payment_status,order_status,transaction_reference,proof_url,inventory_deducted_at,reservation_expires_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(orderId,number,accessToken,idempotencyKey,clean(body.customer_name,120),clean(body.email,180),clean(body.phone,30),clean(body.city,80),clean(body.postal_code,20),clean(body.address,500),subtotal,shipping,tax,total,"Easypaisa","Verification Pending","Payment Pending",storedReference,proof,now,now+48*60*60*1000,now,now)];
  for(const x of items as any[]){statements.push(env.DB.prepare("UPDATE catalog_products SET stock_quantity=stock_quantity-?,updated_at=? WHERE id=?").bind(x.qty,now,x.p.id));statements.push(env.DB.prepare("INSERT INTO order_items (order_id,product_id,title,sku,quantity,unit_price,image) VALUES (?,?,?,?,?,?,?)").bind(orderId,x.p.id,x.p.title,x.p.sku,x.qty,x.p.price,x.p.image));statements.push(env.DB.prepare("INSERT INTO inventory_movements (product_id,order_id,actor_user_id,movement_type,quantity_change,quantity_before,quantity_after,reason,idempotency_key,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(x.p.id,orderId,null,"sale",-x.qty,Number(x.p.stock_quantity),Number(x.p.stock_quantity)-x.qty,"Completed checkout with payment screenshot",`${idempotencyKey}:${x.p.id}`,now))}
  try{await env.DB.batch(statements)}catch(error:any){const message=String(error?.message||"");if(message.includes("INSUFFICIENT_STOCK"))return Response.json({error:"A product has just sold out. Refresh your cart and try again."},{status:409});const existing=await env.DB.prepare("SELECT * FROM store_orders WHERE idempotency_key=?").bind(idempotencyKey).first<any>();if(existing)return Response.json({order_id:existing.id,order_number:existing.order_number,access_token:existing.access_token,total:existing.total,completed:true});return Response.json({error:"Unable to complete the order. Your cart and stock were not changed."},{status:500})}
  return Response.json({order_id:orderId,order_number:number,access_token:accessToken,total,payment_status:"Verification Pending",order_status:"Payment Pending",completed:true},{status:201});
}

export async function GET(request:Request){await schema();const url=new URL(request.url),number=url.searchParams.get("order_number"),token=url.searchParams.get("token");if(!number||!token)return Response.json({error:"Order credentials required."},{status:400});const order=await env.DB.prepare("SELECT * FROM store_orders WHERE order_number=? AND access_token=?").bind(number,token).first<any>();if(!order)return Response.json({error:"Order not found."},{status:404});if(String(order.transaction_reference).startsWith("optional-"))order.transaction_reference="";const items=await env.DB.prepare("SELECT * FROM order_items WHERE order_id=?").bind(order.id).all();return Response.json({order,items:items.results},{headers:{"cache-control":"no-store"}})}

export async function PATCH(request:Request){await schema();const body=await request.json() as any;const order=await env.DB.prepare("SELECT * FROM store_orders WHERE order_number=? AND access_token=?").bind(clean(body.order_number,40),clean(body.access_token,80)).first<any>();if(!order)return Response.json({error:"Order not found."},{status:404});if(order.payment_status!=="Payment Rejected")return Response.json({error:"New proof can only be submitted for a rejected payment."},{status:409});const ref=clean(body.transaction_reference,100),proof=clean(body.proof_url,700);if(!proof.startsWith("/api/media/payment-proofs/"))return Response.json({error:"New payment screenshot is required."},{status:400});const proofKey=decodeURIComponent(proof.slice("/api/media/".length));const proofAsset=await env.DB.prepare("SELECT id FROM media_assets WHERE object_key=? AND kind='payment-proof'").bind(proofKey).first();if(!proofAsset)return Response.json({error:"Upload a valid payment screenshot."},{status:400});await env.DB.prepare("UPDATE store_orders SET transaction_reference=?,proof_url=?,payment_status='Verification Pending',order_status='Payment Pending',admin_note=NULL,verified_by=NULL,verified_at=NULL,reservation_expires_at=?,updated_at=? WHERE id=?").bind(ref||`optional-${order.order_number}`,proof,Date.now()+48*60*60*1000,Date.now(),order.id).run();return Response.json({ok:true})}
